# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:nXUWLmonN0jH7zw72+BmLRMEkwBoVtzFCQdI+msshyfAqvGBvZDLhzQmZjQ0RM0w9elJF9avE+e6aHOcdL3lEl8iM9H93B2bwJFOAhjBnP1oJPpchppabNgjNbgGfzeHkOhdzBoHLyfmiTMaBWvR1nwLYE+iNeVQ5A==,iv:FveUVB2JyC7zYCRe7gLDKhCUwPBnTUztSF4tBNzdvfs=,tag:HPe+s+HfSPCtf/GcdG2E7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNjhsVkJBbFRRSXBFcTBr
            SGRQanRpR2JxOVZ4QkhhQmFEcnY0NCtYZ3hnCm50VWl2QmMwM29mM3Q4R2lwc21K
            UDF4WTBPMlFKK0NUTW10SmtvaFFXNEkKLS0tIE5hSXM5L0pmWXU1a2NXU3NNY3R1
            OGVxT3hkQkVzbStDOTZRY2o2bDRYMnMKaQzT1mSGE23szIl4O6aN8obzexMr8UfJ
            370goLEiLjPnji47bhKj03rgQEDMto/2R/Uw6p0rZL76I5Jwz6mYWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-17T17:56:58Z"
    mac: ENC[AES256_GCM,data:hKU3tf+BMeIeWwgndnxXq8GIp7WKJAWbFGlbO85/oYoGnFBZLrYP7XpCHCyh4Qp/FKOPif4NTskba3VjHhI7YN2AIbqSLhZP/+PF2htV3C21WiYg2GDqxKAttCtu8DUpoK8eCGd+Hjw/XkZCBlvIEWlO+pl0He8ALyO8QCBpxuI=,iv:Xd4/aewvPnQtVavDLr5CmnG2s/Z5dZQGhNeM1mcvWiA=,tag:42ZuHaN6rGNLj2pLtUa+DA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
