apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: keycloak-metrics
  namespace: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  namespaceSelector:
    any: true
  jobLabel: keycloak-metrics
  podMetricsEndpoints:
    - path: /metrics
      interval: 60s
      port: management
