apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
      app.kubernetes.io/instance: keycloak-instance
  endpoints:
    - port: management
      path: /metrics
      scheme: http
