apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keycloak-service-monitor
spec:
  selector:
    matchLabels:
      dashboards: grafana
  endpoints:
    - port: management
      path: /metrics
      scheme: http
