apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-datasource
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-operated.observability.svc.cluster.local:9090
    isDefault: true
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager-datasource
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: alertmanager
    type: alertmanager
    access: proxy
    url: http://kube-prometheus-stack-alertmanager.observability.svc.cluster.local:9093
    jsonData:
      'implementation': prometheus
      # Whether or not Grafana should send alert instances to this Alertmanager
      'handleGrafanaManagedAlerts': false
