# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: grafana-instance-secret
type: Opaque
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:6iNbreY=,iv:WzA3p9sWLqdkShADbE9xVcwoq1eYW6Ho0yCYNh3DBnM=,tag:Q7FPlar+p8Dq77S0Jwg8aw==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:uqVRJcOS/o24/D8eJIV0klrFfJ2O4YiuVOFsC59yi9DDtAPYwUgVAwfKdnoHa/MzQ7eWQB7BqRe44DTBrHDmeo3/UZrgr53xxFMjgoDGSzo=,iv:8/MojDmDZdZGt+1k7UPjfuRNMNMng0wAUYQhwOfMD3I=,tag:t/fsCvqGuk1htsxlm2i+5A==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:RC6Hw41IZqgcOu7htw==,iv:ZlCog82LXvlzyal+HUd8pEt9Uterv5wWC75G6uWxDAg=,tag:FpZrmGwauToNX6dJo7ncbw==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:qPtnvqpBZW7DkQIomoevtvzt5V86VkoG6OpMIGW84aQ=,iv:F2xE+qtI5vJ/a300us0hnh/atIV8A9t8gSMQXy1mKVQ=,tag:Oh4U6e0k2ofj/ZOHFXIp+g==,type:str]
    GF_AUTH_GENERIC_OAUTH_AUTH_URL: ENC[AES256_GCM,data:+Kze7q7JtxNrJr5d3gG7v95JUYZSjeWkdtZwVFqFQlBYA9s1bTPZhv43Qt7dBZdOYOq1beROLaCim1ccRs5kAu51c5cfvKs=,iv:PwWosCI0TvyLwAvxnQ/tETZ9ojM5+S8WmKdk/qlsi1k=,tag:yBY/jK4dOVJrT64IfvIhVA==,type:str]
    GF_AUTH_GENERIC_OAUTH_TOKEN_URL: ENC[AES256_GCM,data:NzK/2gBNCNjtd51gbwgR4iD8S5uKAtmGHOEFkUexxcIEU0ZXnnm/bh91WDbknrF1b6OTg7JA12foGbHffgPRiIeWdn4FXVfE,iv:cGWfB18WZo/q8TnTO8CilP486EVbxQYi8sMwxsdArdY=,tag:S3W1MdwnvhD4zpxiIIcixA==,type:str]
    GF_AUTH_GENERIC_OAUTH_API_URL: ENC[AES256_GCM,data:xVzuZNKFwJrokTUfA4/tAFCJnF9mdJVki6w22dZnVDx48+FbvjTSz6sWgibLu8ZfdlzzdAKDFASnnDW3ZM2fHxTX3GSlt/3+iFf3,iv:jxuoWkMgsnnJOu6rMqYhg/kWwGa6SoKt5a5e0Xk5PyY=,tag:m7uxGxlak7QCXfCmvZquGQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_SIGNOUT_REDIRECT_URL: ENC[AES256_GCM,data:szrHCBVCWH/YF5LxlrlR4JwJbhcsh6sYyCGQjq3xXz3YS5jGPBNEdQ9vONputsGR2ehhbQClkRImJObp+4a/U12WdSkCPmAIOsZUYnbMpwx2RC+/a0cu5U0JF7zBS8k04mu89kqzaMDupv7tLB2Wn+vmhUeQ/Ra0M6joXKajD0KnRcYN+hhE0BUTJ69aQg==,iv:hCJXtG6mBxMMV+WoYMi33iEt75vqJoI74I+8YddiVtU=,tag:qLWRP25tjnfc0QTIwW4BYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNjhsVkJBbFRRSXBFcTBr
            SGRQanRpR2JxOVZ4QkhhQmFEcnY0NCtYZ3hnCm50VWl2QmMwM29mM3Q4R2lwc21K
            UDF4WTBPMlFKK0NUTW10SmtvaFFXNEkKLS0tIE5hSXM5L0pmWXU1a2NXU3NNY3R1
            OGVxT3hkQkVzbStDOTZRY2o2bDRYMnMKaQzT1mSGE23szIl4O6aN8obzexMr8UfJ
            370goLEiLjPnji47bhKj03rgQEDMto/2R/Uw6p0rZL76I5Jwz6mYWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-29T15:01:19Z"
    mac: ENC[AES256_GCM,data:8fosvFwxmNye74TuCsHtnO05CGd1q96TU59mwINimKhqphmggvQ+PcI9CxnbETeCoskwJCo9EI6vfd74wugDzSgx7q6U99TRHi3TdfhpnNaH2+EbSh1fGS722EAV6gLNPl//zU9Ozo12mpbmiQZ614DSIJfCJXiiYKO7Ueky5Ng=,iv:Tg4toTgsjAwUZIcKCN2PdKaYxXpNCKZ2O1kPK/jFwCA=,tag:hJGrCGnmA6H9FXsJycKyPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
