# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: grafana-instance-secret
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:RC6Hw41IZqgcOu7htw==,iv:ZlCog82LXvlzyal+HUd8pEt9Uterv5wWC75G6uWxDAg=,tag:FpZrmGwauToNX6dJo7ncbw==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:qPtnvqpBZW7DkQIomoevtvzt5V86VkoG6OpMIGW84aQ=,iv:F2xE+qtI5vJ/a300us0hnh/atIV8A9t8gSMQXy1mKVQ=,tag:Oh4U6e0k2ofj/ZOHFXIp+g==,type:str]
    GF_AUTH_GENERIC_OAUTH_AUTH_URL: ENC[AES256_GCM,data:+Kze7q7JtxNrJr5d3gG7v95JUYZSjeWkdtZwVFqFQlBYA9s1bTPZhv43Qt7dBZdOYOq1beROLaCim1ccRs5kAu51c5cfvKs=,iv:PwWosCI0TvyLwAvxnQ/tETZ9ojM5+S8WmKdk/qlsi1k=,tag:yBY/jK4dOVJrT64IfvIhVA==,type:str]
    GF_AUTH_GENERIC_OAUTH_TOKEN_URL: ENC[AES256_GCM,data:NzK/2gBNCNjtd51gbwgR4iD8S5uKAtmGHOEFkUexxcIEU0ZXnnm/bh91WDbknrF1b6OTg7JA12foGbHffgPRiIeWdn4FXVfE,iv:cGWfB18WZo/q8TnTO8CilP486EVbxQYi8sMwxsdArdY=,tag:S3W1MdwnvhD4zpxiIIcixA==,type:str]
    GF_AUTH_GENERIC_OAUTH_API_URL: ENC[AES256_GCM,data:xVzuZNKFwJrokTUfA4/tAFCJnF9mdJVki6w22dZnVDx48+FbvjTSz6sWgibLu8ZfdlzzdAKDFASnnDW3ZM2fHxTX3GSlt/3+iFf3,iv:jxuoWkMgsnnJOu6rMqYhg/kWwGa6SoKt5a5e0Xk5PyY=,tag:m7uxGxlak7QCXfCmvZquGQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_SIGNOUT_REDIRECT_URL: ENC[AES256_GCM,data:szrHCBVCWH/YF5LxlrlR4JwJbhcsh6sYyCGQjq3xXz3YS5jGPBNEdQ9vONputsGR2ehhbQClkRImJObp+4a/U12WdSkCPmAIOsZUYnbMpwx2RC+/a0cu5U0JF7zBS8k04mu89kqzaMDupv7tLB2Wn+vmhUeQ/Ra0M6joXKajD0KnRcYN+hhE0BUTJ69aQg==,iv:hCJXtG6mBxMMV+WoYMi33iEt75vqJoI74I+8YddiVtU=,tag:qLWRP25tjnfc0QTIwW4BYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNjhsVkJBbFRRSXBFcTBr
            SGRQanRpR2JxOVZ4QkhhQmFEcnY0NCtYZ3hnCm50VWl2QmMwM29mM3Q4R2lwc21K
            UDF4WTBPMlFKK0NUTW10SmtvaFFXNEkKLS0tIE5hSXM5L0pmWXU1a2NXU3NNY3R1
            OGVxT3hkQkVzbStDOTZRY2o2bDRYMnMKaQzT1mSGE23szIl4O6aN8obzexMr8UfJ
            370goLEiLjPnji47bhKj03rgQEDMto/2R/Uw6p0rZL76I5Jwz6mYWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-29T16:29:40Z"
    mac: ENC[AES256_GCM,data:8ELIx7SCAUbzB0IRrg/x/OdSpflyvWNF+vDtudF5BfGcg9s+A71Rd/RPi5tNh4S8NcjmGgpcknRAROu++4GdqwJu9H6Ces1r6+bRBlxO06I6TMSefTJD+nwX7AI5LDmeWbN6dfxjDurSlsWG6VoqDgzpGnAfY67jQ1WOGRbVAa0=,iv:00gfIDaF1NjkvNOPpdng+TNtEjCFVrmn5MHTi3VBO4A=,tag:E2eyropF2wqJDsC0XABVyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
