# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: grafana-instance-secret
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:frvmnGg=,iv:ZTyvyJhr96gwhekmimoErn48ymo4xbxAeaIdIqq7EV0=,tag:LzP6XIcaGqM8hEKUSR0mHQ==,type:str]
    admin-password: ENC[AES256_GCM,data:UQUdv3168gZUzUhlH3peMvZGd6yfJjPkn/4z9ZvjHCT9bzb84F8qCg5X//smvJmH0lFCxKeUunhdOXuFmmXOasobyiCCDWS6esRdY6Ysq1w=,iv:GJotUySxDaVQ13BZ+tbsMD5/LcT0RlPcRyomr729Goc=,tag:nf29dsAnx8P1mFg2BBEr1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNjhsVkJBbFRRSXBFcTBr
            SGRQanRpR2JxOVZ4QkhhQmFEcnY0NCtYZ3hnCm50VWl2QmMwM29mM3Q4R2lwc21K
            UDF4WTBPMlFKK0NUTW10SmtvaFFXNEkKLS0tIE5hSXM5L0pmWXU1a2NXU3NNY3R1
            OGVxT3hkQkVzbStDOTZRY2o2bDRYMnMKaQzT1mSGE23szIl4O6aN8obzexMr8UfJ
            370goLEiLjPnji47bhKj03rgQEDMto/2R/Uw6p0rZL76I5Jwz6mYWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-12T15:19:57Z"
    mac: ENC[AES256_GCM,data:4uT2UrlWuCYgN8YIR/t1/j7Rf3Vi++GMpelzH/5ckBWAIemFmKtH+M7BTzH4F9mIIU5z0/a9wiPcKOMO+qzvVQ5iAIMZsFHNtrFSDRzBOp/mjXm2kt6jElJGH1UtTsRtLaXge3Hc+U8x/T7A6MF0NXrBdo2sPfKutVLn9xl8an0=,iv:BsB4t4nKkxnG68EOuMn1ptrHCeoM2CW0aUKuEJF6HnY=,tag:GoOvON5N6EYGefIpOFdT0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
