# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: grafana-instance-secret
type: Opaque
stringData:
    admin_user: ENC[AES256_GCM,data:mAokPKc=,iv:n6QI7JMwPpr1HdtWV8BkPL4jow8Cn6vAuy037ibjE2A=,tag:0/qztE2Zu4983+UnXttTVQ==,type:str]
    admin_password: ENC[AES256_GCM,data:xh0utkgBjJbWB+N6icmy2BByzrHFrxq6s/uAFgCN0DO9YR6EeImrs9/XIqmfOrERa351rPhd1bd2i6m8SGRqtq7c0qVeH5GsXWNCTbJ+vjQ=,iv:wJRU7fEJ3yGcxRPK+yR1H2Lk46jnvCBNxoJigMpMMQw=,tag:SIB/VaYGZr/B5p1RI19ezw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNjhsVkJBbFRRSXBFcTBr
            SGRQanRpR2JxOVZ4QkhhQmFEcnY0NCtYZ3hnCm50VWl2QmMwM29mM3Q4R2lwc21K
            UDF4WTBPMlFKK0NUTW10SmtvaFFXNEkKLS0tIE5hSXM5L0pmWXU1a2NXU3NNY3R1
            OGVxT3hkQkVzbStDOTZRY2o2bDRYMnMKaQzT1mSGE23szIl4O6aN8obzexMr8UfJ
            370goLEiLjPnji47bhKj03rgQEDMto/2R/Uw6p0rZL76I5Jwz6mYWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-12T14:48:35Z"
    mac: ENC[AES256_GCM,data:WAFgcQjnBEc48f9Lc5Igc6wSSY/PCLyb+0c6KRWrTOl3tu0l8WHVWhzPcyHwmiPgGo6TTDCfN0BSWNjYFShHJC9Oy9YJyInVJ4tKXYMTlR+iyJceYpq6MC5cpZSlhvjleaQTHWfO7eNKl32mIIFhfAmBrmg1lc07WAz+VtFtks8=,iv:bWN/NaXp5Uss3RO6mdK4DcXSzOKZ86KNEA2waQMfaCk=,tag:VLpJTs9JGlKleEhOeVxLJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
