apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      dashboards: grafana
  endpoints:
    - port: grafana
      path: /metrics
      scheme: http
