apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
type: Opaque
stringData:
    PUSH_ENABLED: ENC[AES256_GCM,data:7r3ywg==,iv:iXhhuYpQ6HPWrsNN6ooY33n33NatIefkDrCcizLiTrU=,tag:R1FmCqHtWHMn0Y29K1Uikw==,type:str]
    PUSH_INSTALLATION_ID: ENC[AES256_GCM,data:qkiwqU1jVNI7g8uP68V7FEQLIVAqK2dnpeTBICd/okSINwDS,iv:bGqSdoy8XJBRJljat+bjPEElDSg4yscA0fsqMKyPL64=,tag:ztYyr25g/izx+Rn0IeHbLg==,type:str]
    PUSH_INSTALLATION_KEY: ENC[AES256_GCM,data:w2gxiVla7dhyilOXKQ775IWpe1Q=,iv:2pmrDcpdO0eutCO4wM6rpDsqhohjvj3+RBsfK0P6eUE=,tag:XZwBhiUUSsB82jIkNHqOiQ==,type:str]
    PUSH_RELAY_URI: ENC[AES256_GCM,data:YshXT6D5CeVA13n7NOC+HoY31lSA4cU+,iv:IEBw9qJXHbyYUUaoHJ31pXtmZ6Pc9qnUVIjGdy7cDyU=,tag:x716O/ObWOHHSY7IU4oiww==,type:str]
    PUSH_IDENTITY_URI: ENC[AES256_GCM,data:EHDdhu9GpIaicZ2oB3ppll2afi7OX0F5pTksbD0=,iv:DJ/3wIIDG/DX9AKD12ctFS0gGJn8USI5xzW+JNRtMqs=,tag:VhhuMKrw3TamyRoDpQS0cg==,type:str]
    SSO_ONLY: ENC[AES256_GCM,data:9gYx/g==,iv:TKuYHihqtxEhEPOKJ7VK9mxP8U8ilG95IxC6uxcRHa4=,tag:fSA9CIpwEZjjlO3n1ONRMg==,type:str]
    SSO_AUTHORITY: ENC[AES256_GCM,data:mWxtk0dfGts+WIkl3Ou50Z7WulrvFOLK/RySztD7Rp9kJhV+nA/N6tFmp3Tp,iv:5vmI2VeJbTCIAOdT7HolMW3qpsP5vZOWPuU7BK0x7uM=,tag:LtZbgUariPluS5IvKqD2aA==,type:str]
    SSO_CLIENT_ID: ENC[AES256_GCM,data:RECkPpMa9A5QDOs=,iv:Cm7dEI8MfWEyMqyXjCeVQAXFquh1shgH1ia3QdTKi3o=,tag:B7pXk8PVCpGp4uyytMokEQ==,type:str]
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:WjMwnBDlOwlPen+fyVLG64HUB/q3lQd6Ss8a3b/GE18=,iv:VZIe2NLYvpb6JBlAVEFY1SQPQWLkLaZ2Tq+Uc/nj0do=,tag:DDorZB6HjStoBnqlMBWjJw==,type:str]
sops:
    age:
        - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUjBJbnJXaVRySURwbWZo
            TVJsQ2FDcG5GbzdZbFl4YkZQVzdEbDdDczBnCkVPcVNvNS9WeUNreHl1eGdNbStz
            NStrMGZKemlHMHBUa3RIUDJUMkR6ZncKLS0tIDM2NVlSbXRqWlR0NEljOWVXb0o2
            c2lTSi9sL0dERWxDdGhQQ21pano4VUUK0PxZtGQxs1K71xqSDD5bVtToUbtAy+qC
            PN0ES+tBXx9YVj8CRcLYZhHgcs+xOFgfwE9iADgwr9GH5a5jWVDKEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T08:19:03Z"
    mac: ENC[AES256_GCM,data:kBe9a8D6bbyGP3rXbHB0YRwfTXD/nl5K5gpzddQSYJ9SKjN3seo4BtKWC8NtWoVewCKnzl5uGeLx1f/oO6aQycwkm4zAqeCKhcOgGQ1ksA2ntR6yjYDpGvJnVhI7M9i4wtUtz4uLgbbTn9HgHPzdYKmVrOyvfNWLephC26ViXC4=,iv:AyR38MCpsFoqvwTImHY6c6WJm1DheoEUY5rz+Eqj2l0=,tag:YDDA6/mbdnzkEmlnm/wFRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
