---
#using ceph as NAS
apiVersion: ceph.rook.io/v1
kind: CephClient
metadata:
  name: pc01
  namespace: rook-ceph
spec:
  name: pc01
  caps:
    mds: 'allow rwx fsname=ceph-filesystem root_squash path=/ext, allow r fsname=ceph-filesystem path=/volumes'
    mon: 'allow r fsname=ceph-filesystem'
    osd: 'allow rw tag cephfs data=data0'
