---
#using ceph as NAS
apiVersion: ceph.rook.io/v1
kind: CephClient
metadata:
  name: pc01
  namespace: rook-ceph
spec:
  name: pc01
  caps:
    mds: 'allow r, allow rw fsname=ceph-filesystem path=/ext'
    mon: 'allow r'
    osd: 'allow rw tag cephfs data=ceph-filesystem'
