apiVersion: ceph.rook.io/v1
kind: CephClient
metadata:
  name: pc01
  namespace: rook-ceph
spec:
  name: pc01
  caps:
    mds: 'allow rw fsname=ceph-filesystem path=/ext, allow r fsname=ceph-filesystem path=/'
    mon: 'allow r fsname=ceph-filesystem'
    osd: 'allow rw tag cephfs data=ceph-filesystem'
