---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  interval: 1h
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.17.5
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    monitoring:
      enabled: true
      createPrometheusRules: true
    cephClusterSpec:
      mon:
        count: 3
      mgr:
        count: 2
        modules:
          - name: rook
            enabled: true
          - name: pg_autoscaler
            enabled: true
          - name: prometheus
            enabled: true
      dashboard:
        enabled: true
        urlPrefix: /
        ssl: false
        prometheusEndpoint: http://prometheus-operated.observability.svc.cluster.local:9090
      storage:
        useAllNodes: false
        osdsPerDevice: 1
        nodes:
          - name: talos-01
            useAllDevices: false
            devices:
              - name: '/dev/disk/by-id/ata-Samsung_SSD_870_QVO_1TB_S5SVNF0R337122F'
          - name: talos-02
            useAllDevices: false
            devices:
              - name: '/dev/disk/by-id/nvme-KINGSTON_SKC3000S1024G_50026B768631A1C3'
          - name: talos-03
            useAllDevices: false
            devices:
              - name: '/dev/disk/by-id/nvme-HFM256GDHTNG-8310A_ND02N449311302802'
              - name: '/dev/disk/by-id/usb-SSDPR-PX_500-01T-80-G_DD56419885CF8-0:0'
      crashCollector:
        disabled: false
        daysToRetain: 14
      network:
        provider: host
      resources:
        osd:
          limits:
            memory: 2Gi
            cpu: 1000m
          requests:
            cpu: 100m
            memory: 500Mi
        mon:
          limits:
            memory: 1Gi
            cpu: 1000m
          requests:
            cpu: 100m
            memory: 320Mi
        mgr:
          limits:
            cpu: 500m
            memory: 1500Mi
          requests:
            cpu: 50m
            memory: 320Mi
        mgr-sidecar:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            memory: 256Mi
        crashcollector:
          requests:
            cpu: 15m
            memory: 60Mi
        prepareosd:
          limits:
            cpu: 1000m
            memory: 400Mi
          requests:
            cpu: 50m
            memory: 200Mi
        logcollector:
          limits:
            cpu: 150m
            memory: 32Mi
          requests:
            cpu: 5m
            memory: 16Mi
        cleanup:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 50Mi
    priorityClassNames:
      mon: system-node-critical
      osd: system-node-critical
      mgr: system-cluster-critical
    toolbox:
      enabled: true
    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: 3
        storageClass:
          enabled: true
          name: ceph-block
          isDefault: false
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          volumeBindingMode: Immediate
          parameters:
            imageFormat: '2'
            imageFeatures: 'layering,exclusive-lock,object-map,fast-diff,deep-flatten' # https://docs.ceph.com/en/quincy/rbd/rbd-config-ref/#image-features
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4

    cephBlockPoolsVolumeSnapshotClass:
      enabled: true
      name: ceph-block
      isDefault: true
      deletionPolicy: Delete
    cephFileSystems:
      - name: ceph-filesystem
        spec:
          preserveFilesystemOnDelete: true
          metadataPool:
            failureDomain: host
            replicated:
              size: 3
          dataPools:
            - failureDomain: host
              replicated:
                size: 3
              name: &ceph-filesystem-datapoolname data0
          metadataServer:
            activeCount: 1
            activeStandby: true
            resources:
              limits:
                memory: '2Gi'
              requests:
                cpu: '25m'
                memory: '256Mi'
            priorityClassName: system-cluster-critical
        storageClass:
          enabled: true
          isDefault: false
          name: ceph-filesystem
          pool: *ceph-filesystem-datapoolname
          reclaimPolicy: Retain
          allowVolumeExpansion: true
          volumeBindingMode: 'Immediate'
          # annotations: {}
          # labels: {}
          # mountOptions: []
          parameters:
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: 'rook-ceph'
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: 'rook-ceph'
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
            csi.storage.k8s.io/node-stage-secret-namespace: 'rook-ceph'
            mounter: fuse
    cephFileSystemVolumeSnapshotClass:
      enabled: true
      name: ceph-filesystem
      isDefault: true
      deletionPolicy: Delete
    cephObjectStores:
      - name: ceph-objectstore
        spec:
          metadataPool:
            failureDomain: host
            replicated:
              size: 3
          dataPool:
            failureDomain: host
            replicated:
              size: 3
          allowUsersInNamespaces:
            - velero
          preservePoolsOnDelete: false
          gateway:
            port: 80
            instances: 1
            priorityClassName: system-cluster-critical
            resources:
              limits:
                memory: 2Gi
              requests:
                memory: 256Mi
                cpu: 100m
          healthCheck:
            bucket:
              interval: 60s
        storageClass:
          enabled: true
          name: ceph-bucket
          reclaimPolicy: Delete
          parameters:
            region: eu-central-1
