---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  interval: 30m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.16.5
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: false
    remediation:
      retries: 3
  values:
    monitoring:
      enabled: true
      createPrometheusRules: true
    cephClusterSpec:
      mon:
        count: 3
      mgr:
        count: 2
        modules:
          - name: rook
            enabled: true
          - name: pg_autoscaler
            enabled: true
      dashboard:
        enabled: true
        urlPrefix: /
        ssl: false
        prometheusEndpoint: http://prometheus-operated.observability.svc.cluster.local:9090
      storage:
        useAllNodes: false
        osdsPerDevice: 1
        nodes:
          - name: talos-01
            useAllDevices: false
            devices:
              - name: '/dev/disk/by-id/ata-Samsung_SSD_870_QVO_1TB_S5SVNF0R337122F'
          - name: talos-02
            useAllDevices: false
            devices:
              - name: '/dev/disk/by-id/nvme-KINGSTON_SKC3000S1024G_50026B768631A1C3'
          - name: talos-03
            useAllDevices: false
            devices:
              - name: '/dev/disk/by-id/ata-SSDPR-CX400-512-G2_G32058003'
      crashCollector:
        disabled: false
        daysToRetain: 14
      network:
        provider: host
      resources:
        osd:
          limits:
            memory: 1600Mi
            cpu: 500m
          requests:
            cpu: 100m
            memory: 800Mi
        mon:
          limits:
            memory: 1Gi
            cpu: 500m
          requests:
            cpu: 100m
            memory: 320Mi
        mgr:
          limits:
            cpu: 500m
            memory: 700Mi
          requests:
            cpu: 50m
            memory: 320Mi
        mgr-sidecar:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            memory: 256Mi
        crashcollector:
          requests:
            cpu: 15m
            memory: 60Mi
        prepareosd:
          limits:
            cpu: 1000m
            memory: 400Mi
          requests:
            cpu: 50m
            memory: 200Mi
        logcollector:
          limits:
            cpu: 50m
            memory: 32Mi
          requests:
            cpu: 5m
            memory: 16Mi
        cleanup:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 50Mi
    ingress:
      dashboard:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: rook.${SECRET_DOMAIN}
        host:
          name: rook.${SECRET_DOMAIN}
          path: '/'
        ingressClassName: internal
    priorityClassNames:
      mon: system-node-critical
      osd: system-node-critical
      mgr: system-cluster-critical
    toolbox:
      enabled: true
    cephBlockPools:
      - name: ceph-blockpool
        storageClass:
          isDefault: false
          name: ceph-block
        spec:
          failureDomain: host
          replicated:
            size: 3
    cephBlockPoolsVolumeSnapshotClass:
      enabled: true
      name: csi-ceph-blockpool
      isDefault: false
      deletionPolicy: Delete
    cephFilesystems:
      - name: ceph-filesystem
        spec:
          metadataPool:
            failureDomain: host
            replicated:
              size: 3
          dataPools:
            - name: replicated
              failureDomain: host
              replicated:
                size: 3
          preserveFilesystemOnDelete: true
          metadataServer:
            activeCount: 1
            activeStandby: true
            resources:
              requests:
                memory: 1Gi
                cpu: 35m
              limits:
                memory: 2Gi
                cpu: 100m
        storageClass:
          enabled: true
          isDefault: false
          name: ceph-filesystem
          reclaimPolicy: Delete
          allowVolumeExpansion: true
    cephObjectStores:
      - name: ceph-objectstore
        spec:
          metadataPool:
            failureDomain: host
            replicated:
              size: 3
          dataPool:
            failureDomain: host
            erasureCoded:
              dataChunks: 2
              codingChunks: 1
          preservePoolsOnDelete: true
          gateway:
            hostNetwork: false
            port: 80
            instances: 1
            priorityClassName: system-cluster-critical
            resources:
              limits:
                memory: 2Gi
                cpu: 35m
              requests:
                memory: 256Mi
          healthCheck:
            bucket:
              interval: 60s
        storageClass:
          enabled: true
          name: ceph-bucket
          reclaimPolicy: Delete
