---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  interval: 30m
  timeout: 25m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.16.5
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: false
  values:
    monitoring:
      enabled: true
      createPrometheusRules: true
    cephClusterSpec:
      mon:
        count: 3
        allowMultiplePerNode: false
      mgr:
        count: 2
      dashboard:
        enabled: true
        urlPrefix: /
        ssl: false
        prometheusEndpoint: http://prometheus-operated.observability.svc.cluster.local:9090
      storage:
        useAllNodes: true
        osdsPerDevice: 1
        # nodes:
        #   - name: talos-01
        #     useAllDevices: false
        #     devices:
        #       - name: '/dev/sda'
        #   - name: talos-02
        #     useAllDevices: false
        #     devices:
        #       - name: '/dev/nvme0n1'
        #   - name: talos-03
        #     useAllDevices: false
        #     devices:
        #       - name: '/dev/sda'
      crashCollector:
        disabled: false
        daysToRetain: 14
      network:
        provider: host
      resources:
        osd:
          limits:
            memory: 4Gi
          requests:
            memory: 2Gi
        mon:
          limits:
            memory: 1Gi
          requests:
            memory: 512Mi
        mgr:
          limits:
            memory: 2Gi
          requests:
            memory: 512Mi
    ingress:
      dashboard:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: rook.${SECRET_DOMAIN}
        host:
          name: rook.${SECRET_DOMAIN}
          path: '/'
        ingressClassName: internal
    priorityClassNames:
      mon: system-node-critical
      osd: system-node-critical
      mgr: system-cluster-critical
    toolbox:
      enabled: true
