---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-filesystem-ext
  namespace: rook-ceph
  annotation:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  storageClassName: ceph-filesystem-retain
