apiVersion: v1
kind: Secret
metadata:
  name: echo-server-sec-secret
type: Opaque
data:
  client-secret: ENC[AES256_GCM,data:MJmZIitpg8Bj9oXP+oM4mgSP9qGrQIccorJcvbwe4Cw=,iv:hRSyx1gwcbPrXnbpO0UnNwNeaMnXrPWqVqNcec1JIKw=,tag:WAd0u+M4eN5ndb3ZRkFQUQ==,type:str]
sops:
  age:
    - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0U1Y1WnlDU1hBRjlZc1JL
        N3p2TS9GK3VpR1psV0lMTHJOa0U5ektpclQwCnJNNXlOMW5hU3pGU00yRW52ajFT
        Yk9lZW5FaVYvVEN3YWtxS2M1NElLb0EKLS0tIG9LblJaRVJOUEp5VkdBM0dZN1hY
        K3JnYk1KZk9YV09ZUkxNb1pldG9zWW8KpqXeM0EGKx1SO4K43qCqhfexy8CcgUpE
        7hEKLW8bB8l8c9cD/8lCdcKR0yy1DmTD3Fd0rAcDw8Z1749G0kerWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-27T20:05:03Z"
  mac: ENC[AES256_GCM,data:bAUx7SldujDItlBooWMMH+OOYDNGa64tJl1gHknR5VbjWrE13UPZPeUHyzX3nFBKr/10GK43gtA2xUIlzXWPfZdtKB1Cl2B4TNhySu42Hd9LwuiS9GS3XTzRiOIcbre2L7fhj7h65vax2tKMFIcoPq8FogpvSc7RT+2MzIGIr5E=,iv:Q9FJmSuKHXe7VbwiXL+G8RRIxo8meVAqaQALwK8VElo=,tag:A0NABZ7kPcFYvHQqTmKxWQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
