---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: echo-server-sec
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
  oidc:
    provider:
      issuer: 'https://auth.${SECRET_DOMAIN}/realms/home-ops'
    clientID: 'echo-server-sec'
    clientSecret:
      name: 'echo-server-sec-secret'
    redirectURL: 'https://echo-server-sec.${SECRET_DOMAIN}'
    cookieDomain: '${SECRET_DOMAIN}'
