---
originRequest:
  originServerName: 'external.${SECRET_DOMAIN}'

ingress:
  - hostname: '${SECRET_DOMAIN}'
    service: &svc https://envoy-kube-system-external-e7092cdf.kube-system.svc.cluster.local
  - hostname: '*.${SECRET_DOMAIN}'
    service: *svc
  - service: http_status:404
