---
originRequest:
  originServerName: 'external.${SECRET_DOMAIN}'

ingress:
  - hostname: '${SECRET_DOMAIN}'
    service: &svc https://envoy-envoy-gateway-system-external-7d05cf23.envoy-gateway-system.svc.cluster.local
  - hostname: '*.${SECRET_DOMAIN}'
    service: *svc
  - service: http_status:404
