---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    groupBy: ['alertname', 'job']
    groupInterval: 10m
    groupWait: 2m
    repeatInterval: 12h
    receiver: discord
    routes:
      - receiver: discord
        matchers:
          - name: severity
            value: critical
            matchType: =
      - receiver: 'null'
        matchers:
          - name: alertname
            value: InfoInhibitor
            matchType: =
  inhibitRules:
    - equal: ['alertname', 'namespace']
      sourceMatch:
        - name: severity
          value: critical
          matchType: =
      targetMatch:
        - name: severity
          value: warning
          matchType: =
  receivers:
    - name: discord
      discordConfigs:
        - apiURL:
            key: discord_webhook_url
            name: alertmanager
    - name: 'null'
