# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager
type: Opaque
stringData:
  discord_webhook_url: ENC[AES256_GCM,data:KD+vFsP88dEXQ6V+KugAJY36RpbkQfuAvpxHPip4JXXE205Dpmfp3iWpKHlH8eK3x8beASQj2qFJKxip01WgjkpP8Gzz/xHzVP9K0eIbIDI7viQA4NlEVi+O8PfA2OkpIYSeS9GJXFc+1mn/443ZIMfNP8aybocgbA==,iv:vjrSBVHGDoTgHuEZp1QSpcy60A2USGCbGwn+7c2bvAw=,tag:YYTx4TtJ5JQ1Pxe3yA+cLA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZG9WMndNcVRWNEpOb0Rx
        S24yYXdWMHVrcFFBenEvT3hTRFdzcVR4ZENBCi81SlJ4RXB0VVFwQUQrM0FEZDZ0
        UFR2dWQ5aGFlQ0RBVjE5ZGw0V1hDb0UKLS0tIDNucHdLM1NpMlc0TUszQkhMZG9U
        Smp3WEh4UHRrZFlaRFlsenNhc09RRFkKLZY1eXG0AjWHbFem3yjFkK9fQmKTEW1z
        DNqU56XR7aCRAbhtI7cyDey2Wzsgr/selFKPocSeIRTKpy30s/8qdA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2025-04-23T18:07:54Z'
  mac: ENC[AES256_GCM,data:hw8UOxvQwcSjBwhf1JuzwWcqoHtD0N8VuxsLZtCSMxdXJ0wMXI7M2EfqjzlZSpJryLyxlAdQ4pjou+MZeTfVlwVLYCBN0HmvIvzRN4PQH9HR4A+UxY/z/oDsy0/66iTSVkHwoiR8Wdsjehd97wMXF9e2u8GFoBVa00po3eSaqzE=,iv:m62sEEpB84rOworLQnWOgfEbCVvdgBGEsl/kIKhjKuk=,tag:juzKEU3fbZnuK7sbx/PuTQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
