# ghcr.io/vmware-tanzu/charts/velero:9.0.1
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: velero
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 10.0.5
  url: oci://ghcr.io/vmware-tanzu/charts/velero
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: velero
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.12.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    configuration:
      features: EnableCSI
      backupStorageLocation:
        - name: default
          provider: aws # ceph object store s3
          bucket: velero-bucket
          credential:
            name: velero-bucket-plugin-format
            key: s3-credentials
          config:
            region: eu-central-1
            s3Url: http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc:80
            s3ForcePathStyle: true
      volumeSnapshotLocation:
        - name: default
          provider: velero.io/csi
