apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: k8s-store-velero
spec:
  provider:
    kubernetes:
      remoteNamespace: velero
      server:
        url: 'https://kubernetes.default.svc.cluster.local'
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: k8s-store-velero
