---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
resources:
  - ./filebrowser/ks.yaml
  - ./jellyfin/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./shared/ks.yaml
  - ./sonarr/ks.yaml
  - ./jackett/ks.yaml
