# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:cXScUIKeo2p1+jnYJ3Dy7uw1uNUg4OjakDn/idPuENU=,iv:Rqs9LXCvexHVZrNLWBTONY9RpgM4/+SRqpx820hMzfA=,tag:tk9X1nfs1KOQD/5MedYM1g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuaGtRR0xSbDd2MloxTEVU
        U3Q1QU44Q2g5YXZQYXZIVUc5T2ljRXVkZkRvCnJQZ2ZkR04yZXpPUGJiVm5mTk1Z
        RHVXTTBFQUd6bFh0eUVQQVZPRTNkaWsKLS0tIHVJazFuU0VYVXJzZEFod2RTQnJF
        d1VQZG04YU53OXExb0lXU1A1c0oyNkkKcZ+UbdVHJxlGEqFNnFfClfpC9cmyLzcm
        xq22cPanzTo517j5d7ONhH05OnUXjp/tahHE6ROBrZfXQWQatZaDAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T15:52:17Z"
  mac: ENC[AES256_GCM,data:gClHAek7RV2/cCA2UIUbMgupr5JTX4rEImreHEYC3DlZps2tSoB7m/+agPVAxctvYFqW6aCHgKZscqfisD/ZIcvVECy/m3PPyhC4Rl+QhX29JXQBhHwCA9cN0n/Ncx6PfFPu2dQRZi6CUAWAryLz5FVMwE/gWhKCpu3hQeUaq3Q=,iv:fKu1ZEq6pppdd5OeSKCklCXU3eI+v4/O9+5q7xCsW0k=,tag:sXKEwSGVATgKFmWWy5YaHA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
