# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:bjQ3Rz8VOA/RdC/345esfmmZ3/n/fL0yRO5FUYpmV2w=,iv:l32We7HpiCvWCRXWnlPnR7RTDilzUSm3GF9YO6b+m34=,tag:uEIjXm/729Xje/hC5ohl3w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15fl7zsdyzqk4uy2yjmx7y4dwd9pghwg6xcuuurgwemp95wgq8ulsd0nfk9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaFREenB2TGdKbnQrcDdW
        U2JqWXdzaGxPbVgwM084MmoydDFHT0pKMEZRCm56UzNmTk1XVTQ5dS8vYUk0SlFx
        a3RDNmhQRTJjWDd3SDMwZTFiSkMrQkkKLS0tIGlOMXA1elhSemhjWUI5eFFpcTI1
        UXB1OUpHMjJmS0tMdyttZ21yajJ6QzQKpySGO5sPV6u0sVZhyuu9bpXHzN17jxE4
        eAKtn0tqb92sDQ+YdsD6VL8IsPYJi1NzqY3Xam9Q0SR6Ap0FuJxgig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-11T11:00:47Z"
  mac: ENC[AES256_GCM,data:vd96uTCipmUWMGNf+Ia3Fz9cfLUxUaIQ5iqvrhVh2xHxm14Boa17EemKE55cCYnJbgkgfQV1I1/CevdacmfLAMlKWKDU8cDlQt6x5qlaA5PRTZJVlcdExO7RdcUwDU7W7/OPH2r1qyFH8tliaw94nREZigIUCw3Fq/K48GUqWi8=,iv:E/PgSMFutHVgAx1CVUMYfs06+YvxGnYtM6bNsAF7eAs=,tag:nWGQ7seJI5pHN1NnE36+aQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
