# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:cnsjncUd5Zl3raqc6zSvk+pRaY6uYDH/nQ0X1dl3aKw=,iv:Oyn28gHYeGme8Zi/lN8lZBM29OOJwGF/F1wZCHPDcY4=,tag:hiYDs8TZcSK7iXj4tiDZfg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNGtkWFJQU2U0L3pLbzBu
        ajAvSDlpYVlFdnRQRDdjczZZa0t5Z1Q5dkFJCkJ1blZjUGJLNVRRbytqUXFFZ1Az
        eDU5cXluRW5CY2xNWTBnUlNaS3diZmcKLS0tIGtFazRGVnNuQTdNWUVWZVd1cjFa
        TjU5WHV2T2M2UnRKNVZCYzFiNmYxYUkKNLg4GW7DXFYBEBVTgd0NrD8kKdUH3zU6
        q38uhNAJhAj5OSbkkFQidtKR5at5xFcTyXinI+hIR41Y50NG1tWImg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-06T20:31:41Z"
  mac: ENC[AES256_GCM,data:qK18Et+N8CTaywk7wfAqubJP41wRyfUuMi+ZVr9FltxphPUV5hv5+UT40/h5+3mFyYbFKLl9098kTOpS9XuZgwlsI9sXotzPuPVavIYLMCeMd/uTLGVCb8GZmBOYWdmAsWj2cJ3/f6tY3sgIQSsiwz1ETP1RBqJba6/I5FQ7uCU=,iv:4JivlNm8O65gdqxWP10FeTCM7pEg2qs+B4tglOWgsfk=,tag:6khYKpRfaQ2e5WP9Y30U1A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
