# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:gnaeqX0PoSlUQIQudREtnFtxrDe3ilIC7oo/T1K8GTY=,iv:BeXU6cIGFv8TVk4jQGzJU0Ze7xGla5sOArFi3rCkIoE=,tag:0jsWsAFQ7PKkWOYTjYAzsA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VXpnakx0Q3l3dUhEL2FC
        TUhSUGlKc1pCUjl4YlNDWHU0ZlVVZlhmM25vCkZXV2pZZ21LOTlaWXZPcjFiL3ZB
        bDJHakljMG9waG1iMk9sckl4OVdxWmsKLS0tIHdIMWFTRFBNcHBmUWNFNkYrbFNo
        M3ZwbGZiU3E5Q25PWW9GT2RWQ0w1eUEKrWk/9lSet4O3ZUoGVyZc2Qtc7j12Lr77
        4Hzaqx26TYxBU1gHfdc6iXkcmjebc31CGGZQ++PIIsoQCPqLwFmLMg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-06T22:17:03Z"
  mac: ENC[AES256_GCM,data:e8SjtL1+/5j/nsTNatDzaLmyMKZrp4CBj6cKKeabfKxUbE+i5nVIHsshy8LvIHbrB/0FmPDUbLzOP45wl7m+2mQwY0cDDnGvoPHhU2u2pIdMK3TBo7YIXt8GRNmc3kXdXNVi7frwIqcWuiFhHIxTSPnKjIIrdZqEXSGaoDzXYS0=,iv:v47/HHDNFS/P0y1g8IvbOwZgIhIUaE6UgwKobq/uEQs=,tag:YujII3AkXuVWxEd6c7mrNA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
