# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:KTBjjzCe9b4Oy6W1c+BQiXU6Dtkv5ehD5agm+GdoEFE=,iv:A7eLM/mhCNkBFFJb3uM/hRtY8DukzOGbqn2NZWrHHRw=,tag:Ej8kXK4RKkTRJMgzUW89Ow==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MEhwTndzbXg5VXp6SmdH
        Sy9GREZEeWttRkFWUkc2WStzL054NnRlS0hnCnZzbVY4c0lCQjB0SnJKNVZvbDhN
        ZWpBUm4vY0ZBTkZaVmdOam15THFCM1EKLS0tIHNGSlJJM1MvMDF0UUE1Skw1NkdP
        dmdRK0NHdmxzTGdobTUwWXdPRFpjWGsKwBXA5//nQ2v+8T1mzLwbRX1FP5Vlo1yj
        5fYXfp6QT544qSXQDEm4zJAdFaAI0G43o1WpHgaS65oLLflu99mctA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-06T21:59:44Z"
  mac: ENC[AES256_GCM,data:Nfx3+tm0S9x5QjZsbqB2clWcEWhSQLrSCVRxyPfc9ii39wPLmqvoVTtWlz2+p2CytI7xupF+mwPRXcC+HF2eYP96+TIGTamAtgKrM1RjbRb3MNmpJ9Q+R/7FhLLVpI5Qz4NAld12TRIkzZVBFpf3v/LZhdbhSFZliWEXpp5KyzQ=,iv:P+9BPJp5UZg8sP42w4eEOr1qVYpfRLNWZarGl7gmG64=,tag:ZW2IO65nJoEfyKAm2Hlj+g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
