apiVersion: builtin
kind: LabelTransformer
metadata:
  name: label-transformer
labels:
  pod-security.kubernetes.io/enforce: privileged
fieldSpecs:
  - path: metadata/labels
    create: true
    kind: Namespace
    namespaceSelector:
      matchNames:
        - rook-ceph