# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:JJkJeWGt9GqQI7OD0U7nnDRDY26pNDo4ThgDAkVB58F1qAoJfmXqIA==,iv:FyRzF8yWp61MzZhJpErb0e1AyYr3YU0bYpOVBKC7M08=,tag:aIIU/cEp4orzmPhVM6VcBg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQzU5STRVcGZvWVVLSWll
        emlDUjJ2S0gxWG9ISFB5SWl3TGc1U2ZXb3g4CmRFN3huWmdmSXVRY1Y3dTVxdGo5
        U1p6MXRhMjJsSEtzYlgyc3h1cXc0K28KLS0tIE9PcGt5WGNTMDZmR3drWG43Uk5N
        ZWNNV0N1cE10cUM4T3ZhQnYrWmRwbFEKW3rH43+pzfMklpyqokGlQcBzjjhyvS+A
        nU4imxX/gLMAFkfJATyq2Xet9rT/qgOLulUqymVWvJf0MqbJ24wKkw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-06T20:31:42Z"
  mac: ENC[AES256_GCM,data:utwaXNJN9AUEWO9zvdNozh3/UbpOiAfQkbUIcX+F/1jt1hT/MGDt5c2cfAXrrBrXr8gzgPZT+5oGSKoglXRhwhvzBH66fnXVOjlJHyOAps5htMz/6vBGHuEhcGXf0vSkvpXOoaIGJ5fyRiuWHRYe/NYmd+ZRnBrR84KAmVVNaaM=,iv:xVcU1uZhToiUsNWe/xNCF2bN2sJGVCV4YMaTAjD7yKQ=,tag:N8pP/RmbK0V1NVEVkSapfA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
