# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Z5kcvltI3EnAq0wi0gYFs+POBVPbjs/j/fPUIvDPNK2QSM/RiL7fIA==,iv:Emj0RoLaps5q5fORK9midlZtZLp7dMmV5lRXxfAtWFQ=,tag:ladrh3HmuF0OMFF/6J245w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSTVMTHVPT0dGZHdXbGNz
        azMzNlhPS2VMRkFZY2xWQUY0eWVTL0R2ZWw4CnNNZmRObm5FSkVVMUx6b1FsWDNp
        THBYUzdPS0EyWVJOS1pDNUI0MCszemcKLS0tIDF4aTlZa2psL2J2bnQ0OHkyaGFi
        V0hHZUViZ204T1F4RVh4dWRHQi8zRzgKmjwNGwndNKSs/Vpr46zlnQgdxoAnqDun
        fxh+gr873H5JJikBMURYkzHU8g4iUVYJZuF5kI4LngLfv+H2PgIaCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-06T21:59:44Z"
  mac: ENC[AES256_GCM,data:fzcpxAldCsPr8XvjeCx/gAVQeqnr7YGNZxaiy6UlmT5eQ3a+V2DDz4E8VmpOaTgjwtcXRL6VnZSlt9jsVeHEK1YYZwohL0StUdjuSNaWkNQOKdvUsGlVM6usgPGH73xh+LCTJ+PXSy0Gbew3P+X8747Dgtus9Ian5GbyWcB71WY=,iv:BMbFOgTjd7tPXozSZQFzR+s6So/J4sgfrgmfhVfBJrk=,tag:uBauEZKUeQWdcbxwUGP6DA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
