# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ERLFjGFYG/lA8koMxAly2plA54Dhx8+tf0br6vd7kHpu3OCfgUgKqA==,iv:LTjANzp9T/q9ieh6h+OdLLfYP5K06Fy9WS9lX5vsXIE=,tag:yXuSR6Q3ndlTc08rqegWPw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNHJ5UE1xeWVMY2Z2ZzI0
        Q3NmL24waGtFeURmdDNCVWpiODNla2s0eEd3ClFGaGp3UW1hQTlLZjFoTCtDQ3Zn
        a1V4VWZmeDV4TXBjMGhnekd0TGNlaEEKLS0tIE4wdnBTWDQxSHZqU3oxbmQzYWFl
        dFM2Zm8wSkU5bzhjZlZFWC9Nd3ExaDAK3/fXLeh2qXFk7AcXU7Y1RN62zNRQf7mv
        1aX2YSqMT6QAayUDYZ+83foOQITkTl6djFq5g3dZKVDId4OCYkzIRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T15:52:17Z"
  mac: ENC[AES256_GCM,data:AZhVeb9/Z2WkwmkRagCBduf63as7POLLgB51UwvBmuCB7MTebaDqGgHE4eulNsBDQjpF/HOZjibLpbxBzFLKHY5QnWoDW/7XRF3Qa6EWPzQLX5I4BUAo6zLzC9NSzNSU1ttB8vS/GK5BcesVyGl6GQqL6tXUbT+jToO+nlZnhBc=,iv:q9mJ8Qoa7jyxkL2i9b80l7K6CCfuI/oBFYMEuocUxaU=,tag:S4gz8hCljKggyNUo/VkyRg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
