# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:7Faz2eVLN6ajt3ehoZSt6PCDfIh8vYq9UTe0csVNL3beT8N4g+qlwA==,iv:2duxjtJSh8PaYaeeRkFX92aV9hOlWzzlg/PCd1fkVmU=,tag:zEvE5bUoG4q+1omV080wiQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZS0gzeEMxT1FubUg2SFJK
        ZGFUY1RmWS9uSlEyMTN2RlY4a1pFRGlyb0JnCkhMWHl2dnVNOG1PdmN4dlBnV3F0
        KzdGUFBHazhGb2w1SGxsN0Z1Y2ZHV2cKLS0tIDd4SXlvK05hNG9ESEFmSWp6VDJn
        ZjdXMzBHRjRTUGcvd1ZFamFhSVJ4K1kKlcm7ksPTncpEOUoZMohthKNqwO+ZE78H
        8sv2nTRFTvRVmSXjTKpBPar+HGwCdQ2obLEnj+LjTwx7lrADYxNjSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-06T22:17:03Z"
  mac: ENC[AES256_GCM,data:+5iE2DF9IIY8bu8dMNI4NMVEEXwrgGf3W1glzmsbPf/iwv7NuDrkW581jOjsZBQn2ylqduBUM+wUhjyNb1dp3zYOyz7nXz3PWInyaxytwwCps3jU3rldmH6rkYKBj3feGHo4TXMQAKZnbyGScch3fCSH8yZ6mGjAjL7VnRqQCao=,iv:q5AHoD32u2zTEV2SucbOS1NweHPPkQqm6ZTJtl0DlBU=,tag:xjnHFIO1/NcYK1DLtPjY9A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
