---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs-monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs-monitoring
      version: 0.4.13
      sourceRef:
        kind: HelmRepository
        name: openebs-monitoring
        namespace: flux-system
  values:
    kube-prometheus-stack:
      install: false
    node-problem-detector:
      install: false
    metrics:
      serviceMonitor:
        enabled: false
    openebsMonitoringAddon:
      lvmLocalPV:
        enabled: true
        dashboards:
          enabled: true
        alertRules:
          enabled: true
        serviceMonitor:
          enabled: true
      zfsLocalPV:
        enabled: false
      dashboards:
        enabled: false
      npd:
        enabled: false
