---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: 0.4.12
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  values:
    kube-prometheus-stack:
      install: false
    node-problem-detector:
      install: false
