---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autobrr-config
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: autobrr-queue
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ''
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - ms_mode=secure
  csi:
    driver: rook-ceph.cephfs.csi.ceph.com
    volumeHandle: autobrr-queue-ext
    volumeAttributes:
      clusterID: rook-ceph
      fsName: ceph-filesystem
      staticVolume: 'true'
      rootPath: /ext/.h/queue
    nodeStageSecretRef:
      name: rook-csi-cephfs-node
      namespace: rook-ceph
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autobrr-queue
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ''
  volumeName: autobrr-queue
  resources:
    requests:
      storage: 1Gi
