apiVersion: v1
kind: Secret
metadata:
    name: autobrr-secret
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:7AqfUSLbaM8eDfYzaVDXoXUjMScHSniJbnLhmE+++ay47OVuRtraM+yK7BYx/krhemz2XRaoLR691Erw4lVksn6wMpEmXJrXWBrUCzjvX7V5mKc3Sgc=,iv:zPgMjfKY40b797/DrIDw9SSzXzsEoCib7+Tqv1dNI5c=,tag:ygZI+QXjJMF9oMu2R09cTQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSmg4MW1YOU5GNGc4Titi
            RkNwcCtvWGRoYjFkT0pabzkxbWRNZzBFeDBVCkNWS2F1NGxGeXljbkxRNGhjbUpu
            amYwV1l0OU1mQitIdHZsZjZUYS9QZVEKLS0tIFQrb2RQRHRvNngwKzVtblhHNTlt
            QWp3YnpkcFhUZmZ0QTg0YkhpT2tqUTQKQ+L7UZUWgz3mx65Ze8lxKp3yPR1/scSw
            HFXpoEKzx7iSx2AFqjT55OtwrCc261plJd8rbE5hiVl/DVw06Il0nw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T21:57:27Z"
    mac: ENC[AES256_GCM,data:a4zSop0DiJhuT/MQCeH4WDyIsM+5ZDhKXW/O8tGtEmm0kiG4YILhT5Ic1vthrzKt8/GvrQ2dLiGlXa8n6gMB8PsdqCRcOo1YLNOO5YyGQrGjGuEujYLGnjvbCdcBdfnIqyPWOWDg0DNrifzTmagf3REpM91EpG+te98SRCqlEl0=,iv:gTmEuQTo2gHVplOLYb07K4K+KBs11gOfva0JE+CmCpw=,tag:tFVaFSedieLcNBgTOir3DQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
