# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:coRUwxFUjQrPA2BmWhz8KDLqaCZHx84+awrTDJQPEx8Oe4H8,iv:6Eimmiv9lCw3xQAUcB7gKlHvtB2dstHvD1fS91WwGr8=,tag:XPr6Z4cs3kyjHJoZ1mvT7A==,type:str]
  credentials.json: ENC[AES256_GCM,data:rw0TtIv+6ECvuGg7IVGz/LWNs5A5wj8iH0LVPByUiXxrU68ByGXjeHgFIHfgmINZwU/C0KZa8tEUDdZ7kEE7Y38Kb1qHyZWTgSvwrZ/YOn3CJzq7qd/cBxpRkiNmtqC8SK9uv2pj1dZtSQ3qX0wKxrXleMBZTIjT6EY6qJ1thfVxq/sWDY6TiJ3AC2QLsiegpsqgEoyXbRFmCwauNoE91MHodXb3CNvSv6S3BfXakA==,iv:o+Hu/5gov7EiutetJaDXjCzgfiAntyHNy1A4lrOHqOY=,tag:dd5fOWB1IkAZOVv0jtrzLw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15fl7zsdyzqk4uy2yjmx7y4dwd9pghwg6xcuuurgwemp95wgq8ulsd0nfk9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbThndDNOT3VodXlqR243
        RktIT1BSUTQ4MTl4Y0V5STNXTjFaTC9FT1ZrCmFuS0ZudmdGaDF0azV3MzJOZE83
        b0w3QzJTS0ZqVFFaUTRYVnVkMVlQQXcKLS0tIFVZNHBtVkVIK2FMcTBic3JxSU9P
        d3Fua3BtcnF2Y1oyTUdMWkEwejcrRDAKdSjQ66ahrEQ4lXZ7TKywwZz7t3RdQJz0
        F7ATqEa1i1Zkpx3NleEi0F6NZL7fVCy311Ho0uHmlhw03zemWmHxRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-11T11:00:47Z"
  mac: ENC[AES256_GCM,data:wd6gK9gTSvsDOgbY4ge6mRjy9Zk5IVo95IkqqZuC0xOFW+rvrn+mqbvNEnWT1ok7xuve00T2vUzHyhav2Oj5OO+FiJEGnfsptp5oSdwYvcVWghGsEPgZNT1a91oyR7b2uVZ117joO6ete13UnifsNN/vNwJcazIDeLVOBhBTXGE=,iv:vMn7IVgU/aoJ6Rz8zjwEqk6E2k/eKZ6qQDtFJUsd/NE=,tag:73ayQzHeXuzNGqy3obiRRg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
