version: '3'

tasks:
  suspend:
    desc: Suspend specific resource types in all namespaces
    vars:
      resources: '{{.CLI_ARGS | default "kustomization helmrelease"}}'
    cmds:
      - |
        resources="{{.resources}}"
        namespaces="$(kubectl get ns -o yaml | yq '.items[].metadata.name')"
        for ns in $namespaces; do
          for rt in $resources; do
            echo "Suspending $rt in namespace $ns"
            flux suspend "$rt" --all -n "$ns" || true
          done
        done
    silent: false

  resume:
    desc: Resume specific resource types in all namespaces
    vars:
      resources: '{{.CLI_ARGS | default "kustomization helmrelease"}}'
    cmds:
      - |
        resources="{{.resources}}"
        namespaces="$(kubectl get ns -o yaml | yq '.items[].metadata.name')"
        for ns in $namespaces; do
          for rt in $resources; do
            echo "Resuming $rt in namespace $ns"
            flux resume "$rt" --all -n "$ns"
          done
        done
    silent: false