---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - ./keycloak-operator/ks.yaml
  - ./keycloak-operator-crds/ks.yaml
  - ./keycloak-instance/ks.yaml
