---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: 6.6.9
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    deploymentAnnotations:
      reloader.stakater.com/auto: 'true'
    image:
      flavor: fpm-alpine
      # renovate: datasource=docker depName=nextcloud
      tag: 31.0.2-fpm-alpine
    ingress:
      enabled: true
      className: external
      annotations:
        external-dns.alpha.kubernetes.io/hostname: &hostname 'cloud2.${SECRET_DOMAIN}'
        external-dns.alpha.kubernetes.io/target: '${SECRET_PUBLIC_IP}'
        external-dns.alpha.kubernetes.io/cloudflare-proxied: 'false'
        nginx.ingress.kubernetes.io/proxy-body-size: 4G
        # CORS breaks webdav https://github.com/nextcloud/helm/issues/410#issuecomment-1654965117
        nginx.ingress.kubernetes.io/enable-cors: 'false'
        # Keep this in sync with the README.md:
        nginx.ingress.kubernetes.io/server-snippet: |-
          server_tokens off;
          proxy_hide_header X-Powered-By;
          rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
          rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
          rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
          rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
          location = /.well-known/carddav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /.well-known/caldav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
          }
          location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
            deny all;
          }
          location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
            deny all;
          }
      path: /
      pathType: Prefix
    nextcloud:
      configs:
        local.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array(
              0 => '127.0.0.1',
              1 => '10.69.0.0/16',
              2 => '10.96.0.0/16',
            ),
            'overwriteprotocol' => 'https',
            'overwritehost' => 'cloud2.${SECRET_DOMAIN}',
            'overwrite.cli.url' => 'https://cloud2.${SECRET_DOMAIN}',
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
            'maintenance_window_start' => 1,
            'default_phone_region' => 'PL',
          );
      hooks:
        before-starting: |-
          ./occ status
      host: *hostname
      extraEnv:
        - name: REDIS_HOST
          value: nextcloud-memcache.default.svc.cluster.local
        - name: REDIS_HOST_PORT
          value: '6379'
      defaultConfigs:
        apps.config.php: false

      existingSecret:
        enabled: true
        secretName: nextcloud-secret
    cronjob:
      enabled: true
    nginx:
      enabled: true
      config:
        custom: |-
          server {
              fastcgi_param front_controller_active false;
              location ~ ^/apps/files {
                rewrite ^/(?!index) /index.php$request_uri;
              }
          }

    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      existingSecret:
        enabled: true
        secretName: nextcloud-database-app
        usernameKey: user
        passwordKey: password
        hostKey: host
        databaseKey: dbname
    persistence:
      storageClass: ceph-block
      enabled: true
      size: 5Gi
      nextcloudData:
        storageClass: ceph-block
        enabled: true
        size: 5Gi
    phpClientHttpsFix:
      enabled: true
    livenessProbe:
      periodSeconds: 30
    readinessProbe:
      periodSeconds: 30
    startupProbe:
      enabled: true
      initialDelaySeconds: 5
      failureThreshold: 30
      timeoutSeconds: 5
