# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
type: Opaque
stringData:
    nextcloud-username: ENC[AES256_GCM,data:bbBoPiM=,iv:Xe6f1T8EzU6Rv/Xio+ZxWRFUqcNPtmx57ir7sVK58EI=,tag:Qv2Ttttcy1l9gSE+fgyl/w==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:WAlfXeGL/NFYhExvag+O8s9cD4LW7WdV5Y8IqUXoOnkb9xxmCTaGZA==,iv:dz29d3UCBRR7snaUl1JNAKalGNeQ0qBW+0rizEiD/AU=,tag:v69LGiLfQnp1yjE/Ry0WLA==,type:str]
    OIDC_clientid: ENC[AES256_GCM,data:bVZAptm6FhnMP5WUlbY=,iv:zNV7xmIMwSRc5LjNp+GXJW9rqbAyemm7GRxv3F+ylYc=,tag:GYemWWCCPQqEpCGcaOWyUQ==,type:str]
    OIDC_clientsecret: ENC[AES256_GCM,data:w8a6UcTMRWQlfmHxPkErzqO5HY1DQKG3bu2bKTqp6rM=,iv:jigitIzbO8dBFZUw7HCJe46PIne8WtXH+EJ1F8/vEqo=,tag:hQRoj9o5L6myg2lDf2Q+iA==,type:str]
    OIDC_discoverurl: ENC[AES256_GCM,data:FoVGiC7irg06GLxXHnPmHhGakiuAyxtbX+U0lN3fpM0StUlHLxBuvM4j2fL9MTqxglsHUhy5u7mLrKagyhTgIS2Koim+pkrrzgG7,iv:NLlwgF0Jxr6PGqzY9BSulbS1VyfPxQyJt39FmDKAYf8=,tag:dW7Fl2L5Hf1DVBm/iTjtkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNjhsVkJBbFRRSXBFcTBr
            SGRQanRpR2JxOVZ4QkhhQmFEcnY0NCtYZ3hnCm50VWl2QmMwM29mM3Q4R2lwc21K
            UDF4WTBPMlFKK0NUTW10SmtvaFFXNEkKLS0tIE5hSXM5L0pmWXU1a2NXU3NNY3R1
            OGVxT3hkQkVzbStDOTZRY2o2bDRYMnMKaQzT1mSGE23szIl4O6aN8obzexMr8UfJ
            370goLEiLjPnji47bhKj03rgQEDMto/2R/Uw6p0rZL76I5Jwz6mYWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-28T17:38:39Z"
    mac: ENC[AES256_GCM,data:3Q8dn12j/jD5Htpt+sT6sDQKQJLPG1Qg8rA7kRWx6jsMjTUtZlMdUhOuX2j3yIbnaVemmbP/eOJvsux1TvwcMmE1+05EopbKEvDwqzeTAPYwndXnyd0XGSiTAvrWaxXWCqVK9e0j8QliRCLwjjJAcU3Zvflu9g4FZlP2g2NjcbQ=,iv:JFy8hBIZNRS/4LNgfYqXf7A3Rcs4cb5LXfiJmb+rbMc=,tag:I4iZti+LXITKtEBtHJg5xg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
