# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
type: Opaque
stringData:
    nextcloud-username: ENC[AES256_GCM,data:bbBoPiM=,iv:Xe6f1T8EzU6Rv/Xio+ZxWRFUqcNPtmx57ir7sVK58EI=,tag:Qv2Ttttcy1l9gSE+fgyl/w==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:WAlfXeGL/NFYhExvag+O8s9cD4LW7WdV5Y8IqUXoOnkb9xxmCTaGZA==,iv:dz29d3UCBRR7snaUl1JNAKalGNeQ0qBW+0rizEiD/AU=,tag:v69LGiLfQnp1yjE/Ry0WLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNjhsVkJBbFRRSXBFcTBr
            SGRQanRpR2JxOVZ4QkhhQmFEcnY0NCtYZ3hnCm50VWl2QmMwM29mM3Q4R2lwc21K
            UDF4WTBPMlFKK0NUTW10SmtvaFFXNEkKLS0tIE5hSXM5L0pmWXU1a2NXU3NNY3R1
            OGVxT3hkQkVzbStDOTZRY2o2bDRYMnMKaQzT1mSGE23szIl4O6aN8obzexMr8UfJ
            370goLEiLjPnji47bhKj03rgQEDMto/2R/Uw6p0rZL76I5Jwz6mYWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-19T14:57:03Z"
    mac: ENC[AES256_GCM,data:w75RFAnHIISBejqMa7ek1I17LJ1+xDMFNCTo2bGIUNO+p/dRQoeLZ4BYZzdKBMDStSObckSgOFlbec3cfwMqLfWktOPbFr4ADDYsKvUwtitVo4jc7xt5bAilG9cv7CFntSKwpIC+b13vy3chYKGlchdHLZrkITXED5c1wW/Toeo=,iv:/OB6+aN6yH2bOCYgzVs9jjRT87jSSyaBkrlVc1rDFOQ=,tag:AlyEclK/sUEw7ZzNEGt0Hg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
