apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
spec:
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
spec:
  resources:
    requests:
      storage: 3Gi
  storageClassName: ceph-block
