apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-filesystem
