---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: mimir
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/grafana/helm-charts/mimir-distributed
  ref:
    tag: 6.1.0
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
spec:
  interval: 1h
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: mimir
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    global:
      extraEnvFrom:
        - secretRef:
            name: mimir-bucket
        - configMapRef:
            name: mimir-bucket
    metaMonitoring:
      dashboards:
        enabled: true
        annotations:
          k8s-sidecar-target-directory: /var/lib/grafana/dashboards/Mimir
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
        mimirRules: true
        mimirAlerts: false
    minio:
      enabled: false
    kafka:
      enabled: false
    rollout_operator:
      enabled: false
    mimir:
      structuredConfig:
        multitenancy_enabled: false
        ruler:
          alertmanager_url: http://kube-prometheus-stack-alertmanager.observability.svc.cluster.local:9093
        ruler_storage:
          storage_prefix: ruler
        common:
          storage:
            backend: s3
            s3:
              endpoint: "$${BUCKET_HOST}:$${BUCKET_PORT}"
              bucket_name: "$${BUCKET_NAME}"
              access_key_id: "$${AWS_ACCESS_KEY_ID}"
              secret_access_key: "$${AWS_SECRET_ACCESS_KEY}"
              insecure: true
        ingester:
          ring:
            replication_factor: 2
          push_grpc_method_enabled: true
        ingest_storage:
          enabled: false
        limits:
          compactor_blocks_retention_period: 14d
          max_label_names_per_series: 50
          max_global_series_per_user: 500000
          ingestion_rate: 50000
          ingestion_burst_size: 1000000
          ruler_max_rules_per_rule_group: 50
    alertmanager:
      enabled: false
    gateway:
      service:
        labels:
          prometheus.io/service-monitor: "false"
    ruler:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          memory: 256Mi
    distributor:
      replicas: 2
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 512Mi
    ingester:
      replicas: 2
      zoneAwareReplication:
        enabled: false
      persistentVolume:
        enabled: false
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          memory: 2Gi
    querier:
      replicas: 2
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 512Mi
    query_frontend:
      replicas: 1
    query_scheduler:
      replicas: 1
    store_gateway:
      replicas: 2
      zoneAwareReplication:
        enabled: false
      persistentVolume:
        enabled: false
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 1Gi
    compactor:
      replicas: 1
      persistentVolume:
        enabled: false
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 1Gi
    chunks-cache:
      enabled: true
      allocatedMemory: 256
      resources:
        requests:
          cpu: 50m
          memory: 320Mi
        limits:
          memory: 384Mi
    index-cache:
      enabled: true
      allocatedMemory: 256
      resources:
        requests:
          cpu: 50m
          memory: 320Mi
        limits:
          memory: 384Mi
    metadata-cache:
      enabled: true
      allocatedMemory: 128
      resources:
        requests:
          cpu: 25m
          memory: 192Mi
        limits:
          memory: 256Mi
    results-cache:
      enabled: true
      allocatedMemory: 256
      resources:
        requests:
          cpu: 50m
          memory: 320Mi
        limits:
          memory: 384Mi
