apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:EMH33ycBFJ231ExbAQV8+/6cDNU3bBto5LMaPklsYEE=,iv:vHsCsUrehz1xXxysx+x6Nh9qdqkR9vTlKVScPrpT1tg=,tag:zxuitBnvkoPOSH/VphdAsg==,type:str]
sops:
    age:
        - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0U1Y1WnlDU1hBRjlZc1JL
            N3p2TS9GK3VpR1psV0lMTHJOa0U5ektpclQwCnJNNXlOMW5hU3pGU00yRW52ajFT
            Yk9lZW5FaVYvVEN3YWtxS2M1NElLb0EKLS0tIG9LblJaRVJOUEp5VkdBM0dZN1hY
            K3JnYk1KZk9YV09ZUkxNb1pldG9zWW8KpqXeM0EGKx1SO4K43qCqhfexy8CcgUpE
            7hEKLW8bB8l8c9cD/8lCdcKR0yy1DmTD3Fd0rAcDw8Z1749G0kerWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-03T13:17:21Z"
    mac: ENC[AES256_GCM,data:qVH1sfgbD8FxZaS5EdpC6LCNw2zc/VnaZjfKYlZTMLNfTuFx7IXszK+QkpmYUzeXXfl1SLG78Qqlt7t8JABQr+wux1GzfzW7hX1ImcqqO5UUIuCDmO0DpKzDB5TrGXuWzY8pah+1f1xT+jLf6kz0MB8Mk74lhmyw/9tOuy6i92Y=,iv:sYn3QpFHnsLYvsKW/OEzMlLxA9zFv3SjDKGDNes0HJY=,tag:vejceiYV53Z8pHpbkCIIQg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
