---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-data
spec:
  storageClassName: ceph-filesystem-kernel
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
