apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:vYo1w7DF/yDvywAetoXRF1HEoJMAIMFuP9BhwyEKMxE=,iv:IOk0zEWt4Aqsntn9swejykfuwzRqXvdtAnqQJtJHnsY=,tag:L4DmEuRwky/mWYWVI38Uxw==,type:str]
sops:
    age:
        - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0U1Y1WnlDU1hBRjlZc1JL
            N3p2TS9GK3VpR1psV0lMTHJOa0U5ektpclQwCnJNNXlOMW5hU3pGU00yRW52ajFT
            Yk9lZW5FaVYvVEN3YWtxS2M1NElLb0EKLS0tIG9LblJaRVJOUEp5VkdBM0dZN1hY
            K3JnYk1KZk9YV09ZUkxNb1pldG9zWW8KpqXeM0EGKx1SO4K43qCqhfexy8CcgUpE
            7hEKLW8bB8l8c9cD/8lCdcKR0yy1DmTD3Fd0rAcDw8Z1749G0kerWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-03T18:46:59Z"
    mac: ENC[AES256_GCM,data:2y/pu7XmzHpsNeiLauxmkD+htyeuad0WybGK2nSrzvM/t2KPg8BClGSNEhzGrlnu/uJ2ujWa9DxN8imlng7azDvnObQqe3fyI4yLo3wQYcLAM0Q0b+nWswLZf8il/uoZqOzgAUXVlLUsFB9HkRxVHHr0WKbmi4LwFTU8XKNMhWg=,iv:nliMAcl6yfVV5+Wxzck60xC9rswBRA7NMhmdRZbdmd8=,tag:M6ZMhOq5a6dyO58V5fYxaA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
