---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  # Keycloak CRD
  - # renovate: datasource=github-releases depName=keycloak/keycloak-k8s-resources
    https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/refs/tags/26.1.3/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
  # Keycloak CRD
  - # renovate: datasource=github-releases depName=keycloak/keycloak-k8s-resources
    https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/refs/tags/26.1.3/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
  # Keycloak Operator
  - # renovate: datasource=github-releases depName=keycloak/keycloak-k8s-resources
    https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/refs/tags/26.1.3/kubernetes/kubernetes.yml
