# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:geXEnNXCAMMd9KauDw==,iv:Pd9o7EETcy88lNKDSRZvBGItwp8t9h5CyTy+jLhtOMU=,tag:yLjbiD+ty1IL8/L+jQpQxQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:No7oLxzAKxrC0Gj25k5X/d8R,iv:6LPwF+m4bJYxUL4VALQX4id4HI8GT32qrr5vehKdU08=,tag:Z8NUCkhKCDMMb5ArtF9f3A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ryd9WdJ/UDhK8MevBPetXvCMQqZnukDaTK/IJJdXRW+xyNDl,iv:nGGfMEiRGDAYz5xh+U+GIj6dAZL4xznBRk8PMVGv1Us=,tag:VV1zJb5AoTyxPRT+EowmZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15fl7zsdyzqk4uy2yjmx7y4dwd9pghwg6xcuuurgwemp95wgq8ulsd0nfk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMTFxQzlZTXNpa2ZRMEhX
            SE40c0R0SnZJNUhsdlRBcDlEdTJ5TGRGc1ZVClNjd1BtcDVVVTBXRTFSd3prejlz
            WG1QWE5NVmtlRmpud2xxazFOTCtIM3MKLS0tIEM5N3pOdWg1amhDQWNaOXpZT08r
            S3hNNlNjRmoyaWY3OGY1QThFN3RVUFEKl5o1ETytjX+nQuEnPXuFQdTxQdvNAUq8
            u+JkcqdxV1S1IJrlJF814quAz9mkUtOPdBhYESdYcOAIoKrpR/+sYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-22T20:13:31Z"
    mac: ENC[AES256_GCM,data:EhHbgibTUh8lSzHTrj9qNFrYdM/eX4NL7SrjrOAGb2LqdNzwmsiRt8X06lnFKvrnLV10piUDtiM0JN2xs6LZjq5NYd5xZqo4SNCf3biS6Y8GdP0Vi2Myvrnw4m3FvMwRLR305ofLdQhzxu5/Bw2DpMZt4KVSEwHyucIZPRAt2rQ=,iv:JHQ0Cjab4VX9zdXfTkXau3O39rDfmNRkBUp4GaAgiYE=,tag:l8jFPVdZh8Fkf7cFWdeUig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.3
