# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:geXEnNXCAMMd9KauDw==,iv:Pd9o7EETcy88lNKDSRZvBGItwp8t9h5CyTy+jLhtOMU=,tag:yLjbiD+ty1IL8/L+jQpQxQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:No7oLxzAKxrC0Gj25k5X/d8R,iv:6LPwF+m4bJYxUL4VALQX4id4HI8GT32qrr5vehKdU08=,tag:Z8NUCkhKCDMMb5ArtF9f3A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ryd9WdJ/UDhK8MevBPetXvCMQqZnukDaTK/IJJdXRW+xyNDl,iv:nGGfMEiRGDAYz5xh+U+GIj6dAZL4xznBRk8PMVGv1Us=,tag:VV1zJb5AoTyxPRT+EowmZg==,type:str]
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:ZglJ4A==,iv:2m0DyDaJ9DOYTZAbRZvFPoIYndLvubtQ0Cayq+3jnAk=,tag:Yh3jwVKRlOAjPvnU6Pw0qg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15fl7zsdyzqk4uy2yjmx7y4dwd9pghwg6xcuuurgwemp95wgq8ulsd0nfk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMTFxQzlZTXNpa2ZRMEhX
            SE40c0R0SnZJNUhsdlRBcDlEdTJ5TGRGc1ZVClNjd1BtcDVVVTBXRTFSd3prejlz
            WG1QWE5NVmtlRmpud2xxazFOTCtIM3MKLS0tIEM5N3pOdWg1amhDQWNaOXpZT08r
            S3hNNlNjRmoyaWY3OGY1QThFN3RVUFEKl5o1ETytjX+nQuEnPXuFQdTxQdvNAUq8
            u+JkcqdxV1S1IJrlJF814quAz9mkUtOPdBhYESdYcOAIoKrpR/+sYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-21T20:04:28Z"
    mac: ENC[AES256_GCM,data:5xoc3WFN4eNyK2KQJAUArB2XQObAozRqaGAy3yZIA5DABr+ElgvSGggk9dD8rkMU+rN7yl19h6lY+yBYgMn30OZbhJZlLBHXzciSo7jOmYPoBJAnDYaPG27Lhn3ghjBJaxz6n6cMhpIS7boaaMfTi2iFa3cfQhpQNARjzuRcmWQ=,iv:CzUPwroOkj1REVbCMvVmS6IfNja+dQjCIVoVq1xyv28=,tag:R2/3yU9CaW/CmLWBb4XvZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.3
