# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:B2nhuCm/u0a7x5R559sP8GcPvVbVemvp6szV7yCBRf7z1ORkXfYjGA==,iv:eRFsAyLbgvVMEAkyqgHwksOQh92wVI27TthPLhfn+ao=,tag:58Q8RbT7K66l01InOaM54A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRUtOZmZuVEJTRUtPdzZL
        NXFzZmtOcnY4N2xhT2FjRmRidDlZWWV3SlV3ClRFRjJ0ZlVabXRkdnJGalRiQkd5
        dWVIME9DUmxJRlphVHZNK3Q3cE5tYmcKLS0tIHVWcm55TkhkbXd0K2ZGdjJpaFFX
        RXBnRnlRa1VudjJBZXlTZmFpYWdzaU0KSEk0l8yT0/VwOaXHy9OVOkDiRqTkb/nF
        c5U/5ju4jul6sp7NsiO9wlf4vlYzkuK+PMlMlI9qAonfa7KhqSxCtQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-06T22:17:03Z"
  mac: ENC[AES256_GCM,data:iN+8Swe5JVlzduzWlq1Q3gXxSq2U3x+xGOjS0hkavXt7lBhxGziOsM+sAtGFTwAaENcDsGcYDQzfZpbk+NLGlCDWmq6bX0vP3MDEIynEorXnR8FfIAjW+wripnCf7fkVCRtwI+7zqP8TOFJbLqmifoM4FT0QRlcLySZoDE1U4M4=,iv:J9/NHHMUWRRO/Fq6kR9AhFnZwkZvbrc5zS01NW1/jJo=,tag:pPnZeCRkuKgEyfd3FMLRiQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
