# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:UewfUk5BN/aFdhn6u61E/ciZXCJJAw/BKoO8hle7+9ZbCk9XtCQqJA==,iv:KSOUD7ypL4ah8sLkDvxOR0TfBFSl9oMQU6SeD0xcU1E=,tag:QOICulgyHmaWA46s6K7hBA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UWlRWWRkZFFYSVFIK2N5
        VWFKOUR2NGRXZ252NUhqOXNmRXIvU1RZYWtVCjFuZEluY3VFSEgyMkgrRitnbGNS
        TS9XQVVJYy9EZ2pKTXNEbG15Qldma2cKLS0tIHdTdXd0a0E5OEtKMVF0alRTcE9V
        REhIMFJRM2lZUjN3cURhbmRFSmkvdzgKyOLQJd3VHtG17jYVvIx8xI5fQt+eKKQw
        KKil37HdUSGr8BorNP4bK7O6Cv0xpsZcRnHtjJQ6bgeeLFt+SvFQeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T15:52:17Z"
  mac: ENC[AES256_GCM,data:J6iAyDsUQf86/3kYrZGhF5Z2ZJrkDGew18ht0IWmIMEnKOfe9Dd6pkyL6is9w3lidS6wivj00Oq1NIgZSltYwPQtqjOTD/xlDYdh1XRjlurnsy61ogKE+jV12zx6AGgA1ZDPYVDCo/qh/mb0nCTRxx58D7PFvpR/nRawU/09Jkw=,iv:nxbmyb4TMXn8Xp3KF++EHS0tAVkD+gYK2GXRy/iJPqs=,tag:xCiygndZjoHs3Jve1q84eQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
