# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:0CpMaoeNr8hhDO26tMnYwXEbj+xqla11IuH4Kc4LUb8PaxCZczrxiw==,iv:lJvEn5kvCegDOBD25sdO3JlFZAWuGmB8PJvbAxDpX5I=,tag:xXZjxjXESkoT9z7V+Wf84g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15fl7zsdyzqk4uy2yjmx7y4dwd9pghwg6xcuuurgwemp95wgq8ulsd0nfk9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeU5LMXA0cG1RWlZEMjdz
        RzdId29zTnVvZEhwYUQ5dVRPVDQ0bTl5ckJVCnVXbWR6c1Q5QzRkM2p3M3l3R3hw
        a09KNURwbGVMQStJR1ZzRVllS2EyRjQKLS0tIGtoZUhNMFN5NFlnSDNDVVArT0xV
        WUlROXpyTTg3V2ZPUWlKWm0yU2dheTAKrS4Et/iuGGxqoQCSTIxpwCraJXttkdtc
        GoJgPBR60bhAUIOyHTX2DzcHmsv1S2nxKuoAudNrYWpvLAqN4Q+MhQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-11T11:00:47Z"
  mac: ENC[AES256_GCM,data:hZOzWFQ37whbL94vmyR0bID9jAgMmHBrfHtEPDLsg47IDMaWHUZRkTeQx95Ejf9ce5lvhJceh6Y00WiIHwzxKDNglSfwrYXKriWj/+qLjR/u5ORfQt/N+jvOTrVntIR+aDRr6QWvdjCIsCZjyxSYMMtYjydRJ1ISeZXNeVzGF0k=,iv:Zs6E1cdwJH3CYi7tFq90qXkKcNw2L2dLp1fuqO+kHvs=,tag:Pwgf/cCdRbxrU25r+WsvRQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
