# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:RXS4Cs1W3xgySSyGRfOM7KzYbHh/8Sg7xD1CM6jMnBDnKSWnLEwuYw==,iv://6OqQqhpJv30rBJeDmL+iont3q2N0oAz+TrLmZhE5A=,tag:sRZV0ha5tqiyN1xrLemxHw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadWRZbTFuTVhKRndwc0N1
        UUhlaHlNWlYrVWZqY1BqUTVUVWVLRjJGd1NZCk42TVREMkZ0RkJjVWZwazgvaTQ5
        TVV0UzBXY0tpQlZMZHEwS2JvRUZLL3cKLS0tIGVRNEtRdVRBMWFyYWFBMTRyM04v
        ekZ5aXY3bERvcUhqNmNadDh1bWpJcVEK/kLvjO3IfXdH+4X/XL6HHwm5ig61C7+j
        RAyxg6/9swZv/PeWDQ4B2DQTh3vY4q4ukS68BKuewBz1Uqic6PqCXg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-06T20:31:41Z"
  mac: ENC[AES256_GCM,data:IuuoOOrqa/ZPGaJ3UiriKH094vt5nYzEYFbDq/fgH1l+X/4WXiZeegL6FLiyx9Gl74g3gPOY3R2/wmEDJkptMs5ZWG4gg3ZGeGNKm6oQkXeA5tHwyhZ4gGXqBezm3gAWuSLyPdRMhQQCtumWKZpBFsgFgWvtXNKvESmIBex9T54=,iv:p4XSmTlffec8VvJypH1V0DQNo9w7ZqRmnMxA4lNwBm0=,tag:7YL0UBvqKo+kwAthIQ7gpA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
