# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:fv7h/5VQbkZQxIeAzx0GATGeZzmVgfls9aXTAGcW+YRtr5+3LSNe9Q==,iv:pmMjShalagyYr14EInXtqtAPJ40wRjp2vItcawh/CBo=,tag:s0vyEKD7KbZxlu49bIcW7g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBManloZW9uK29nc3hBMUow
        WExqTlN3Sm96VTUxZldIc3RPT2RQaGlHY3lRCi85c1pjME1zZktzVTc4cTNqV3pT
        enMzeXNkSTloVHlLZ09UUWJKeENYWVUKLS0tIGxxRnR6RHQzWTNsdTR1WStoUkZ0
        cEJ5VGY4NVh6cVV4MnBXRWpPbldJL0UKN4WZwi9HbUKHduZaUit04brxiUyOsTEl
        CfqPBGf9FhTNY8b+Yh8vEs8b67xBizZ69erGwHGBtjMCiMQK9KOVkw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-06T21:59:44Z"
  mac: ENC[AES256_GCM,data:B8fRENTIuo7RHhg+Qz1pVF/I4pq6SR7tNcflGkhg2JChKq2MTqKf1Wve28hIsg6Lq40zW5Hn6D5vH+5vBjYyqrOgwGWkVmB6JBq9/i2AiiUMvYmtJ45IpJAwdRebaWT55oh6QAoVTHHSTvuUW98awFGsnWBCdaW/eDXaDJkpK/8=,iv:XXtXpECGRULOxxE0/Nho+7I6gvdvwiKK9565qeYOykY=,tag:oER+uFFlJ+qxut+Z0vI66Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
