---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jackett
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      jackett:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/jackett
              tag: 0.22.2151@sha256:b60444892d5dce0e92dba120a7e7a097560a6d4dfb78e233c4315433b9d6e9db
            env:
              TZ: ${SECRET_TIMEZONE}
              PUID: 1000
              GUID: 1000
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /Health
                    port: &port 9117
                  periodSeconds: 10
                  timeoutSeconds: 10
                  failureThreshold: 6
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ['ALL'] }
            resources:
              requests:
                cpu: 15m
                memory: 50Mi
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - &url '{{ .Release.Name }}.${SECRET_DOMAIN}'
        parentRefs:
          - name: internal
            namespace: envoy-gateway-system
            sectionName: https
        annotations:
          gethomepage.dev/description: Indexer agragator and cache
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/group: Services
          gethomepage.dev/icon: jackett
          gethomepage.dev/name: Jackett
          gethomepage.dev/href: 'https://{{ .Release.Name }}.${SECRET_DOMAIN}'
          gethomepage.dev/widget.type: jackett
          gethomepage.dev/widget.url: http://jackett.media.svc.cluster.local:9117
    persistence:
      config:
        existingClaim: jackett-config
      downloads:
        existingClaim: jackett-downloads
      tmp:
        type: emptyDir
