apiVersion: v1
kind: Secret
metadata:
    name: jackett-secret
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:0wW/Pikd4p0oQeRmLpEVH3xNpohXz3GdTSWQKI5Stuc=,iv:LOAPNte08jjfwinv6ujs6/uY0W8Mbk4T3uVLGzGcwH4=,tag:E+7nKuzZKs4w7nVJljStGQ==,type:str]
sops:
    age:
        - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0U1Y1WnlDU1hBRjlZc1JL
            N3p2TS9GK3VpR1psV0lMTHJOa0U5ektpclQwCnJNNXlOMW5hU3pGU00yRW52ajFT
            Yk9lZW5FaVYvVEN3YWtxS2M1NElLb0EKLS0tIG9LblJaRVJOUEp5VkdBM0dZN1hY
            K3JnYk1KZk9YV09ZUkxNb1pldG9zWW8KpqXeM0EGKx1SO4K43qCqhfexy8CcgUpE
            7hEKLW8bB8l8c9cD/8lCdcKR0yy1DmTD3Fd0rAcDw8Z1749G0kerWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-04T11:07:12Z"
    mac: ENC[AES256_GCM,data:WfxZ0kr90QQ8UNvRxerwb3DsTNNs41V7djX7liTTDAcAFTxf74CSeAjEaFrdraZOidzRvgt5ipub5M61bHIvsMe7UJZt/Ph9aalFfMUtnWRE7VB80KYsqhIjhJXYJdKVtcmiJJCeRrYz5rbLTClQvl4A2ajmE/ymihTnxX/pXBE=,iv:ei7exOQ10rghGw0LXRz5YfmGdhawzkLSQBXJ3s7s128=,tag:W2seVDEZVfyLWzBi/Hx07g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
