---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./controlplaneio.yaml
  - ./coredns.yaml
  - ./dragonfly-operator.yaml
  - ./external-dns.yaml
  - ./grafana.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./metrics-server.yaml
  - ./nextcloud.yaml
  - ./openebs.yaml
  - ./podinfo.yaml
  - ./rook-release.yaml
  - ./spegel.yaml
  - ./stakater.yaml
