---
# TODO do better after https://github.com/immich-app/immich-charts/issues/165
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: immich
spec:
  parentRefs:
    - name: external
      namespace: kube-system
      sectionName: https
  hostnames:
    - immich.${SECRET_DOMAIN}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: strict-transport-security
                value: max-age=0
      backendRefs:
        - name: immich-server
          port: 2283
# ---
# # yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/externaldns.k8s.io/dnsendpoint_v1alpha1.json
# apiVersion: externaldns.k8s.io/v1alpha1
# kind: DNSEndpoint
# metadata:
#   name: immich
# spec:
#   endpoints:
#     - dnsName: immich.${SECRET_DOMAIN}
#       recordType: A
#       targets:
#         - ${SECRET_PUBLIC_IP}
#       providerSpecific:
#         - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
#           value: 'false'
