---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  annotations:
    kustomize.toolkit.fluxcd.io/prune: Disabled
  labels:
    backup: immich-library # used by velero
spec:
  storageClassName: ceph-filesystem-kernel
  resources:
    requests:
      storage: 160Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
