---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  annotations:
    kustomize.toolkit.fluxcd.io/prune: Disabled
spec:
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 150Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
