apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gallery
spec:
  resources:
    requests:
      storage: 150Gi
  storageClassName: ceph-filesystem
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
