---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich
  annotations:
    kustomize.toolkit.fluxcd.io/prune: Disabled
spec:
  resources:
    requests:
      storage: 150Gi
  storageClassName: ceph-filesystem
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich
  annotations:
    kustomize.toolkit.fluxcd.io/prune: Disabled
spec:
  storageClassName: 'ceph-filesystem'
  volumeName: immich
