apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: immich-library-snapshot
  namespace: velero
spec:
  schedule: '0 3 * * 0' # Every sunday at 3 AM
  template:
    includedNamespaces:
      - immich
    includedResources:
      - persistentvolumeclaims
    labelSelector:
      matchLabels:
        backup: immich-library
    snapshotVolumes: true
    ttl: 340h0m0s # little over 2 weeks
