---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: homepage-config
    behavior: merge
    files:
      - ./bookmarks.yaml
      - ./services.yaml
      - ./settings.yaml
      - ./widgets.yaml
resources:
  - ./configmap.yaml
