---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  render:
    desc: Render Talos machine configs without applying them
    dir: '{{.TALOS_DIR}}'
    cmd: topf render --confirm=false --output ./rendered
    preconditions:
      - test -f {{.TALOS_DIR}}/topf.yaml
      - test -f {{.SOPS_AGE_KEY_FILE}}
      - which topf

  diff:
    desc: Show pending Talos config changes without applying them
    dir: '{{.TALOS_DIR}}'
    cmd: topf apply --dry-run
    preconditions:
      - test -f {{.TALOS_DIR}}/topf.yaml
      - which topf

  apply:
    desc: Apply Talos config to all nodes (shows a diff and asks first)
    dir: '{{.TALOS_DIR}}'
    cmd: topf apply
    preconditions:
      - test -f {{.TALOS_DIR}}/topf.yaml
      - which topf

  apply-node:
    desc: Apply Talos config to a node [NODE=required] [MODE=auto]
    dir: '{{.TALOS_DIR}}'
    cmd: topf apply --nodes-filter '^{{.NODE}}$' --mode {{.MODE}}
    vars:
      MODE: '{{.MODE | default "auto"}}'
    requires:
      vars: [NODE]
    preconditions:
      - test -f {{.TALOS_DIR}}/topf.yaml
      - which topf

  upgrade:
    desc: Upgrade Talos on all nodes, one at a time (asks first)
    dir: '{{.TALOS_DIR}}'
    cmd: topf upgrade
    preconditions:
      - test -f {{.TALOS_DIR}}/topf.yaml
      - which topf

  upgrade-node:
    desc: Upgrade Talos on a single node [NODE=required]
    dir: '{{.TALOS_DIR}}'
    cmd: topf upgrade --nodes-filter '^{{.NODE}}$'
    requires:
      vars: [NODE]
    preconditions:
      - test -f {{.TALOS_DIR}}/topf.yaml
      - which topf

  upgrade-k8s:
    desc: Upgrade Kubernetes
    dir: '{{.TALOS_DIR}}'
    cmd: talosctl --nodes {{.NODE_IP}} upgrade-k8s --to {{.KUBERNETES_VERSION}}
    vars:
      NODE_IP:
        sh: yq '[.nodes[] | select(.role == "control-plane")][0].ip' {{.TALOS_DIR}}/topf.yaml
      KUBERNETES_VERSION:
        sh: yq '.kubernetesVersion' {{.TALOS_DIR}}/topf.yaml
    preconditions:
      - talosctl config info
      - test -f {{.TALOSCONFIG}}
      - which talosctl yq

  reset:
    desc: Resets nodes back to maintenance mode
    dir: '{{.TALOS_DIR}}'
    prompt: This will destroy your cluster and reset the nodes back to maintenance mode... continue?
    cmd: topf reset --confirm=false --full={{.CLI_FORCE}}
    preconditions:
      - test -f {{.TALOS_DIR}}/topf.yaml
      - which topf
