apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:79QDREjvJFTrpfWGsA==,iv:xhjHw4JoD1hdLE0UaHak8dKkYk6ApiD2WP7ir/Ldses=,tag:KG6a8Ii2LAf1LtQbdlJorQ==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:6MXzYzrK+zLrXAco62N5B3Jfze+oB+FBC8JSPeYMygLva/l8,iv:aY4y5FgMGhl/4bid7s9RP9hLxzFa+h06qNzwTX3rKSs=,tag:lSbM/M57k4yg0IxPu9qHxA==,type:str]
  SECRET_PUBLIC_IP: ENC[AES256_GCM,data:8nD5zXhpfTHSIuBTAQ==,iv:DD+D6MyjZsx3D4gfZtEC1jezPsAOeXx0fZy7gmDuIIk=,tag:FQ7wVcgxp+wtLJHFLeO0pQ==,type:str]
  SECRET_TIMEZONE: ENC[AES256_GCM,data:aubpe21fmTIhcJemdQ==,iv:F9byoHd8B9H5p+IJY8iHZieFCdJGIfDod++7GGkMIY4=,tag:KEgUJfyJomU2c7dhFldcgg==,type:str]
  SECRET_VPN_IP: ENC[AES256_GCM,data:8jEhunL06aYBBScl4g==,iv:KiziJsfMAAYabdZUio+ZxMU+Ff995rOhHcPnheLVMeY=,tag:4mb5+h4ipwyt63P+DqTxqg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVDcveW12U3NUSVRpK2Nw
        VXJrRm45bmczcTNpM1FYS3FBVWd0ZElZK2g4CkZsL3JTeXdKZWxHbXVwSFFaR0Rr
        dDhrVXhrU3Nwb0NaSm4vU0gvN1gxV0EKLS0tIGErd0lZZFZRWGYvcWFBR3phaVE1
        OXZtL3gxSE1IYUpnb1NCcXd5S1B5NEkKAwjSHC4pi3TKTrR9SszuEFDz0wJKRCwv
        g1BDcbSXY8YkcuQNvbTf7XMtkoC9pbFE8RdXz7IMrS1d7DnvkWWAVg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-19T16:58:32Z"
  mac: ENC[AES256_GCM,data:pwTPf4jUJAM87b+gArFAKVdS8L9s5EBT/X4ABrgGNs/qC6WHND43cTDbmlbmEnWiOysuc4h/BaAoS2VeZSLumc/+iJ2noeZ5iDrJV4LCX3VV1Y4jgLxBIruEcZuVMK6jBZlb2pE4/VT7K2h7r7MyqvB97dB1tM9VvSDXjX81Ln0=,iv:7u5E2hQUbEzO6JUrxLEiDxcERp335pZyvx4BPRviI9A=,tag:SsCtmEVjv++5F6nj98Qk3A==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
