apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:79QDREjvJFTrpfWGsA==,iv:xhjHw4JoD1hdLE0UaHak8dKkYk6ApiD2WP7ir/Ldses=,tag:KG6a8Ii2LAf1LtQbdlJorQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:6MXzYzrK+zLrXAco62N5B3Jfze+oB+FBC8JSPeYMygLva/l8,iv:aY4y5FgMGhl/4bid7s9RP9hLxzFa+h06qNzwTX3rKSs=,tag:lSbM/M57k4yg0IxPu9qHxA==,type:str]
    SECRET_PUBLIC_IP: ENC[AES256_GCM,data:8nD5zXhpfTHSIuBTAQ==,iv:DD+D6MyjZsx3D4gfZtEC1jezPsAOeXx0fZy7gmDuIIk=,tag:FQ7wVcgxp+wtLJHFLeO0pQ==,type:str]
    SECRET_TIMEZONE: ENC[AES256_GCM,data:aubpe21fmTIhcJemdQ==,iv:F9byoHd8B9H5p+IJY8iHZieFCdJGIfDod++7GGkMIY4=,tag:KEgUJfyJomU2c7dhFldcgg==,type:str]
sops:
    age:
        - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVDcveW12U3NUSVRpK2Nw
            VXJrRm45bmczcTNpM1FYS3FBVWd0ZElZK2g4CkZsL3JTeXdKZWxHbXVwSFFaR0Rr
            dDhrVXhrU3Nwb0NaSm4vU0gvN1gxV0EKLS0tIGErd0lZZFZRWGYvcWFBR3phaVE1
            OXZtL3gxSE1IYUpnb1NCcXd5S1B5NEkKAwjSHC4pi3TKTrR9SszuEFDz0wJKRCwv
            g1BDcbSXY8YkcuQNvbTf7XMtkoC9pbFE8RdXz7IMrS1d7DnvkWWAVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-02T12:40:57Z"
    mac: ENC[AES256_GCM,data:MDFRwBAT1SIVO2xLEMsYQYG6XpB9amsbRRiaVXkBTgmOMK+aMDtBSytRkw23EKTcirbSPI3SWS2Xn23JrMcCQE2UTGfP33IFxDNOBrxMqXdtV6WIy5DhXxtjb1VIVEXo3KyyHuZDCB/w57NnAKc8Fo7WRKKLN683tUy5PosZPv0=,iv:j8zxtfN5kq0uxqsXkvzfZlhiqzV7ySeAEovXYPtW66I=,tag:Q4LxXgQFwjBAVZplWL2cyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
