# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
talosVersion: "${talosVersion}"

kubernetesVersion: "${kubernetesVersion}"

clusterName: kubernetes
endpoint: https://192.168.0.60:6443

clusterPodNets:
  - "10.69.0.0/16"
clusterSvcNets:
  - "10.96.0.0/16"

additionalApiServerCertSans: &sans
  - "192.168.0.60"
  - "127.0.0.1"
additionalMachineCertSans: *sans

# Disable built-in Flannel to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "talos-main"
    ipAddress: "192.168.0.55"
    installDisk: "/dev/sdb"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/76a2de645c973a8619aad40d543a005c02c7ce78ea107667b4e2556f3fcf2189
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "98:90:96:d4:8f:ca"
        dhcp: false
        addresses:
          - "192.168.0.55/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 1500
        vip:
          ip: "192.168.0.60"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/mayastor-patch.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/mayastor-patch-cp.yaml"
