apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:GVjB1Ufo6gXISyuefuG1JhJbIOWJ7b1GBRJ7TYtE0eYtZwiSuPWvmNlQQwOCqGqtAy640jZtiuSoODiwgDO9a6jCiE4tb8BRE1ZrVAoupoIE,iv:/qZu8S7wVjYonkyPJlmvRnYF1xKHtPyBs8N6+Uc0fEQ=,tag:/T46AK0kY82AWq3ofk7whQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15fl7zsdyzqk4uy2yjmx7y4dwd9pghwg6xcuuurgwemp95wgq8ulsd0nfk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYVdVbDN2WkJuckE3Undk
            UU1BKzJBODZpQ0ZpZEE3eVJYZnNPRzZRcFEwCjZtdlNWaktBUS9jRk9Qd1cwdHRE
            RWpIelpzc1lpWUVkVTdyRTBoTGJRaG8KLS0tIEhDbU5xZklhT3hLRmpzeXYwaU1M
            WHQ5cnZSeHFCWVhkcGVNa3V2YTNWYk0KcRO6LCOoe3LkDx+a615GCwWWF/BPYAIL
            a/50JVPPDROqqKcrdeByJ5vrHwyfpwJXkYJBGFruoQ4P9veX7JBHCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-02T15:06:41Z"
    mac: ENC[AES256_GCM,data:0K2+iNpYtR3INgGvybBUKjABD+d4qzjTEmu86wCuI4RTx64jzq81cDJ0CJjtT5vaqhbqXa/LNRklE35CZhK2ROXf0lKgGM5EofuZWMolKeKLVofZmY/FhNW8ieU16SdoU9xpE5DzxBlkGJLBeUL+6e8842ash3izIDjO2d02W6U=,iv:v5znFEY8bOS9WtSom1j7JSN1934WX9YpAn3PnxD90B0=,tag:+2dAL2eXo28O4vXlHpuJbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
