apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:TNXC9CDekp563IaMO05jcagdgvoSl3CW3n2riixLItw6ZFxLc/Y5SOsUJGvhj7WrvwXNxh81wnlVEWAGCf2YX7GqhQXTBbWz3TAqLze+HRLO,iv:ffwW3e5NH498pMtLRpWORIjgO8QTPgFcDX0YtXXNcFI=,tag:GuMQgwz7F1CdXit81PQadg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15fl7zsdyzqk4uy2yjmx7y4dwd9pghwg6xcuuurgwemp95wgq8ulsd0nfk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRVBLSkQxQU4vL1JnL3Qx
            Y0RraFZzcDFtYVpiU00xZ2dxL054Rjk2dzJJClJ4R3JuUjcwTmxTMURLTDJheVRm
            dGJGeDVEajlkM3FTdXJNaWlzaWFHNzQKLS0tIFpBNnA2TjdHSG5rQVNIQlBUekNr
            YlljTjlsYndOQlRMWTd5MnhOUkkyaGMKpSl6L4H78zAeFWATybyJ1zKMD16qmuKW
            yJNw/Ki0z4ITdEuHFlXfBNVRQ1DlzoTCL++f4ydIVsX5tJ+Bt2oTQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-02T22:34:45Z"
    mac: ENC[AES256_GCM,data:ylp7OYt0IKlG8iJIJBKX+asM6eI0QidVMVfpsc5bdZ9YpbMHPfGi2mqAO4e98lL8b6ehN1j3bgEI3w3NiQnqR1ID/wUHgqTki7ozGXTEp2nWLOolw5U0L2R39sSQNmwdoY/g6Pkb8s73mbev2lAiyC78+SOaBdabsPnsRMPnCR0=,iv:JUahya5UYBPGyaguyi0XwxrAUwZBfaQUH3iZ3Yrjs0Q=,tag:AcLIacWlhGjFnSNxkrdT6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
