# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name nextcloud-database
spec:
  description: 'nextcloud database'
  instances: 1
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgresql:16.8-6
  storage:
    size: 5Gi
    # storageClass: openebs-lvmpv #FIXME set storageClass
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: nextcloud
