apiVersion: v1
kind: Service
metadata:
  name: open-webui
spec:
  type: ClusterIP
  clusterIP: 'None'
  ports:
    - port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: Endpoints
metadata:
  name: open-webui
subsets:
  - addresses:
      - ip: 192.168.0.100
    ports:
      - port: 9000
