---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app memos
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      memos:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: ghcr.io/usememos/memos
              tag: 0.26.2@sha256:3eefcc231141369accbd2f42bdc1a4c1e3b291fb6e288ff0deb60afa1b5d4727
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 65534
              runAsGroup: 65534
              capabilities: { drop: [ 'ALL' ] }
            env:
              TZ: ${SECRET_TIMEZONE}
              MEMOS_DRIVER: postgres
              MEMOS_port: &port 5230
              MEMOS_DSN:
                secretKeyRef:
                  name: memos-database-app
                  key: uri
              MEMOS_INSTANCE_URL: &host 'memos.${SECRET_DOMAIN}'

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
        pod:
          priorityClassName: system-cluster-critical
    service:
      memos:
        controller: memos
        ports:
          http:
            port: *port
      grpc:
        controller: memos
        ports:
          http:
            port: 5231
            targetPort: 5230
            appProtocol: kubernetes.io/h2c
    route:
      memos:
        hostnames:
          - *host
        rules:
          - backendRefs:
              - name: *app
                port: *port
        parentRefs:
          - name: internal
            namespace: envoy-gateway-system
            sectionName: https-subdomains
          - name: external
            namespace: envoy-gateway-system
            sectionName: https-subdomains
