# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name immich-database
spec:
  description: 'immich database'
  instances: 1
  primaryUpdateStrategy: unsupervised
  # renovate: datasource=docker depName=ghcr.io/tensorchord/cloudnative-vectorchord
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.2
  storage:
    size: 16Gi
    storageClass: ceph-block
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitSQL:
        - ALTER USER immich WITH SUPERUSER;
  backup:
    volumeSnapshot:
      className: ceph-block
      snapshotOwnerReference: backup
  postgresql:
    shared_preload_libraries:
      - 'vchord.so'
    parameters:
      search_path: '"$user", public, vectors'
