apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:NodfxWbwq49tHae/jWCAfyGVuPRd5of+vJvopaswoEo=,iv:t7HXSVQO/KE2wfRee9L2vPD1lSyVeABWfLiF08sMpV8=,tag:wwOtpTCKLjrf45Mh3zCRNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15fl7zsdyzqk4uy2yjmx7y4dwd9pghwg6xcuuurgwemp95wgq8ulsd0nfk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWlVqdVdJTzMvSEdOZFN1
            bzNCUytyUjRjc1VVc1llblcweGRIdkFHSGo0CmF0QWZ1WnFiRFlwTUR3MGZOd1Z4
            amZ3NldhOEQ3eVROYnFvUUFyZk5XNDgKLS0tIGQrZytMTjRBM1ZpLy85Y0ZoZ3do
            VDFBZFdoaGl3QWhBSlg5S21sWEsrN0kKvgUq16KV1gTjDjYrb/kTrA+asYKD5JFj
            6cFvhSwZk1ndHBWbsQ5Um06a6tkOb+LjblAoU/34I3CT2xkOICQ89Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-02T15:06:41Z"
    mac: ENC[AES256_GCM,data:r7kkSwOCHSDG2pLdz/3qEYEtWAMGGgWNEkJWMd1tEC0UCFGhFowV1NKxdIFbZDGI/WkJMoIuazBTn+7ibPE4ucq6/bAbXssfvgHPxuVP+COXGPDElxkV1WWZvgyxVVpjDCGQ1I+93T4YzjBxVRJJPEpHu4lhkGQbuckQRtpQaow=,iv:zFld9J6zB6iZ6Zo661SEDqMSdUBHr5jdLSrjfGaAE9g=,tag:yVOfJ9eWR33yBuRfAq7Flw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
