apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Q/EowpIVhf9rqfs/Hplupvzc6ECSwXB4MAHpFxbvw74=,iv:uVzPvvy69m8R2GvXI+z5tc7G9wvQgtN6L9t1+c49TtQ=,tag:hlOhuFusOqGDn9uHSGHMYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15fl7zsdyzqk4uy2yjmx7y4dwd9pghwg6xcuuurgwemp95wgq8ulsd0nfk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZXE0SXE0a0w1alBLazRs
            VmdSZ0hYNTlYUVdYcjB5bkp0Y2ZqZFNLVEU4ClU4bGtNRi90Z2ZUZlRCZ3FrNm10
            YmFDTUNFTitjWUtwenJwTTlwb2ZrdzgKLS0tIEZHWmlzQzZHTmN2L1RrOGlsWGJT
            RnVKWnZvNVRMUmI5REVscFVlQVpabkUKvPREhvmTt12fsibM3or+N4lBjfMRdqiS
            ydpyvQjJYUdwzCj3yUV6YycFzgspq0NIvyd3mhqqPSmUq6ThnmgpYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-02T22:34:45Z"
    mac: ENC[AES256_GCM,data:NvWUi4/C5PC6rRWXAjchsYTir6MVmafuKr/AmAiaLA3S4iMTbaAlox8XzAxoJCnguGbyJpO/LPnE5CcIocnTzkciGHrWyP08pc1CTXCq5KrPbHQ+y9SPitZaFDcJg/ee1CUGDxH4gOk2pWOeElXBCmUvyZwYrmjV44RBZ+UPlh8=,iv:dYlP5O2uMD23GvNs4PJhdp/mn2VvG9UjttYL+rO3KjY=,tag:enKqI4mQBzYLB4hGyso4Gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
