---
apiVersion: v1
spec:
  containers:
    - name: debug-${node}
      image: docker.io/library/alpine:latest
      command: ['/bin/sh']
      stdin: true
      stdinOnce: true
      tty: true
      securityContext:
        allowPrivilegeEscalation: true
        privileged: true
      volumeMounts:
        - mountPath: /rootfs
          name: rootfs
        - mountPath: /run/containerd
          name: containerd
  dnsPolicy: ClusterFirstWithHostNet
  hostIPC: true
  hostNetwork: true
  hostPID: true
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: ${node}
  volumes:
    - name: rootfs
      hostPath:
        path: /
    - name: efivars
      hostPath:
        path: /sys/firmware/efi/efivars
    - name: containerd
      hostPath:
        path: /run/containerd
