---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  bookmarks.yaml: |
    ---
    - Bookmarks:
      - k8s-at-home-search:
        - icon: kubernetes
          href: https://nanne.dev/k8s-at-home-search/
          description: Search KAH HelmReleases
      - onedr0p home-ops:
        - icon: github-light
          href: https://github.com/onedr0p/home-ops
          description: onedr0p HomeOps Repository
      - bjw-s Chart Values:
        - icon: github-light
          href: https://github.com/bjw-s/helm-charts/tree/main/charts/library/common#values
          description: app-template Helm Chart Values
      - NixOS Search:
        - icon: nixos
          href: https://search.nixos.org
          description: Search NixOS Packages and Options

  docker.yaml: |
    ---
  kubernetes.yaml: |
    ---
    mode: cluster
    gateway: true

  services.yaml: |
    - Internal:
      - OPNsense:
          href: https://192.168.0.1
          description: Firewall and routing platform
          icon: opnsense
          widget:
            type: opnsense
            url: https://192.168.0.1
            username: {{HOMEPAGE_VAR_OPNSENSE_KEY}}
            password: {{HOMEPAGE_VAR_OPNSENSE_SECRET}}
    - Services:
      - echo-server:
        - echo-server:
            name: Echo-server
            description: An HTTP and WebSocket server for testing
            href: https://echo-server.${SECRET_DOMAIN}
            namespace: default
            podSelector: app.kubernetes.io/controller=echo-server,app.kubernetes.io/instance=echo-server,app.kubernetes.io/name=echo-server
            icon: mdi-server-network-outline
        - echo-server-sec:
            name: Echo-server
            description: OIDC secured echo-server
            href: https://echo-server-sec.${SECRET_DOMAIN}
            namespace: default
            podSelector: app.kubernetes.io/controller=echo-server,app.kubernetes.io/instance=echo-server,app.kubernetes.io/name=echo-server
            icon: mdi-server-network-outline
  settings.yaml: |
    ---
    title: Dashboard
    theme: dark
    color: slate
    headerStyle: clean
    target: _blank
    disableUpdateCheck: true
    hideVersion: true
    layout:
      Bookmarks:
        style: row
        columns: 4
      Applications:
        style: row
        columns: 3
      Services:
        style: row
        columns: 2
        echo-server:
          style: row
          columns: 2
          header: false
      Internal:
        style: row
        columns: 3
    quicklaunch:
      searchDescription: true
      hideInternetSearch: true
      hideVisitURL: true
  widgets.yaml: |
    ---
    - search:
        provider:
          - google
          - duckduckgo
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
