---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  bookmarks.yaml: |
    ---
    - Bookmarks:
      - k8s-at-home-search:
        - icon: kubernetes
          href: https://nanne.dev/k8s-at-home-search/
          description: Search KAH HelmReleases
      - onedr0p home-ops:
        - icon: github
          href: https://github.com/onedr0p/home-ops
          description: onedr0p HomeOps Repository
      - bjw-s Chart Values:
        - icon: github
          href: https://github.com/bjw-s/helm-charts/tree/main/charts/library/common#values
          description: app-template Helm Chart Values
      - NixOS Search:
        - icon: nixos
          href: https://search.nixos.org
          description: Search NixOS Packages and Options

  docker.yaml: |
    ---
  kubernetes.yaml: |
    ---
    mode: cluster
    gateway: true
  services.yaml: |

  settings.yaml: |
    ---
    title: Dashboard
    theme: dark
    color: slate
    headerStyle: clean
    target: _blank
    disableUpdateCheck: true
    hideVersion: true
    layout:
      Bookmarks:
        style: row
        columns: 3
      Services:
        style: row
        columns: 4
      Network:
        style: row
    quicklaunch:
      searchDescription: true
      hideInternetSearch: true
      hideVisitURL: true

  widgets.yaml: |
    ---
    - search:
        provider:
          - google
          - duckduckgo
