apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretName homepage-secret-external
spec:
  secretStoreRef:
    name: cluster-store-default-ns
    kind: ClusterSecretStore
  target:
    name: *secretName
  data:
    - secretKey: HOMEPAGE_VAR_NEXTCLOUD_KEY
      remoteRef:
        key: nextcloud-secret
        property: HOMEPAGE_VAR_NEXTCLOUD_KEY
