---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./homepage-config
  - ./configmap.yaml
  - ./externalSecret.yaml
  - ./helmrelease.yaml
  - ./rbac.yaml
  - ./secret.sops.yaml
  - ./securityPolicy-secret.sops.yaml
  - ./securityPolicy.yaml
