# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  annotations:
    external-dns.alpha.kubernetes.io/target: &ip4 192.168.0.240
spec:
  gatewayClassName: envoy
  listeners:
    - name: http-subdomains
      protocol: HTTP
      port: 80
      hostname: &subdomains '*.${SECRET_DOMAIN}'
      allowedRoutes:
        namespaces:
          from: Same
    - name: https-subdomains
      protocol: HTTPS
      port: 443
      hostname: *subdomains
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: '${SECRET_DOMAIN/./-}-tls'
  infrastructure:
    annotations:
      lbipam.cilium.io/ips: *ip4
