---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
  annotations:
    external-dns.alpha.kubernetes.io/controller: none
spec:
  parentRefs:
    - name: internal
      namespace: envoy-gateway-system
      sectionName: http-subdomains
    - name: external
      namespace: envoy-gateway-system
      sectionName: http-subdomains
  rules:
    - filters:
        - requestRedirect:
            scheme: https
            statusCode: 301
          type: RequestRedirect
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homepage-redirect
spec:
  parentRefs:
    - name: internal
      namespace: envoy-gateway-system
      sectionName: http-subdomains
    - name: external
      namespace: envoy-gateway-system
      sectionName: http-subdomains
  hostnames:
    - ${SECRET_DOMAIN}
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            hostname: hompepage.${SECRET_DOMAIN}
