---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name filebrowser
  namespace: flux-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      filebrowser:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          filebrowser:
            image:
              repository: filebrowser/filebrowser
              tag: v2.41.0@sha256:b7e05896700acf278bc4ee90cac1e13f17d7a983dfbe5744ee3690ee11dce766
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ['ALL'] }
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
            env:
              FB_LOG: stdout
              FB_ROOT: /media
              FB_NOAUTH: 'true' # quote
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    service:
      filebrowser:
        ports:
          http:
            port: 80
    route:
      filebrowser:
        hostnames:
          - &host 'files.${SECRET_DOMAIN}'
        rules:
          - backendRefs:
              - name: filebrowser
                port: http
        parentRefs:
          - name: internal
            namespace: envoy-gateway-system
            sectionName: https
    persistence:
      data:
        enabled: true
        existingClaim: media
        globalMounts:
          - path: /media
      config:
        enabled: true
        existingClaim: filebrowser
        advancedMounts:
          filebrowser:
            filebrowser:
              - path: /database
                subPath: database
              - path: /config
                subPath: config
