apiVersion: v1
kind: Secret
metadata:
    name: filebrowser-secret
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:6sDg7QXJvZ3m5yZLcNIjsLW2/HnvqoGz9nfjf+ENk70=,iv:baBzRn+MTjC5J8cX7Ui9+DZ6Z7K7xbdgbsnzK2Bn+J4=,tag:mgsrJtaOxFzZYoTaxsttlQ==,type:str]
sops:
    age:
        - recipient: age15ahzvyl5k64janfg4qjqzzszuhwwjh6th5mn7eaxzndha3e02g3q577nnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0U1Y1WnlDU1hBRjlZc1JL
            N3p2TS9GK3VpR1psV0lMTHJOa0U5ektpclQwCnJNNXlOMW5hU3pGU00yRW52ajFT
            Yk9lZW5FaVYvVEN3YWtxS2M1NElLb0EKLS0tIG9LblJaRVJOUEp5VkdBM0dZN1hY
            K3JnYk1KZk9YV09ZUkxNb1pldG9zWW8KpqXeM0EGKx1SO4K43qCqhfexy8CcgUpE
            7hEKLW8bB8l8c9cD/8lCdcKR0yy1DmTD3Fd0rAcDw8Z1749G0kerWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-11T07:14:21Z"
    mac: ENC[AES256_GCM,data:4HpojRU+wIB7PGmE/JiEOiM2zq2KOfrIr9dZtfKy3YVy0UIEZjSEr2zORXPJpk7xzTfSiMiB/T7L8M0z1+dokw3zbRf4sCPQfKgnwBgHk3dWcuvJSNAO4nrWgjeT7GD/zDSbI9zmNMM6joEZAhTApupEkfKNvvyto4gumB/KewE=,iv:OLc0fMOQnTPS22dpzHdzhKym6D23Xzy9UlXuZpO8r78=,tag:VpflWGq3/ntJakmczq47Bg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
