---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: nextcloud-memcache
spec:
  # renovate: datasource=docker depName=ghcr.io/dragonflydb/dragonfly
  image: ghcr.io/dragonflydb/dragonfly:v1.33.1
  replicas: 1
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
  args:
    - --maxmemory=$(MAX_MEMORY)Mi
    - --cluster_mode=emulated
    - --proactor_threads=1
    - --dbfilename=dragonflySnapshot
  resources:
    limits:
      memory: 256Mi
  snapshot:
    persistentVolumeClaimSpec:
      storageClassName: ceph-block
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 400Mi
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nextcloud-memcache
  labels:
    app: nextcloud-memcache
spec:
  selector:
    matchLabels:
      app: nextcloud-memcache
  podTargetLabels:
    - app
  podMetricsEndpoints:
    - port: admin
