---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/issuer_v1.json
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cilium-hubble-selfsign
spec:
  selfSigned: {}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cilium-hubble-ca
spec:
  isCA: true
  commonName: Cilium Hubble CA
  secretName: cilium-hubble-ca
  duration: 43800h
  renewBefore: 8760h
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: cilium-hubble-selfsign
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/issuer_v1.json
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cilium-hubble-ca
spec:
  ca:
    secretName: cilium-hubble-ca
