# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:itcvUjNg3xUQyyTW1lUqW7GcLQXmyXm0y3vwaqSEytJteIlZZhCYBg==,iv:a9YvSFpl8Qs7A6YMHBFtEQpsVSNDJZmNZKIWa8IbBUg=,tag:jIU7Joh/hRAgxaUaJrIHCQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15fl7zsdyzqk4uy2yjmx7y4dwd9pghwg6xcuuurgwemp95wgq8ulsd0nfk9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMFhzcU5BMHdZd3I5bFdI
        UEV4eEc0MXc2UktjU21ZMERqd21pdTMwSTBBCm00V1dmOWJzVGZ0S0RoaXV0UjdH
        aGp2akZPS2FFRDZPQzQ2WGxDbC9UamcKLS0tIHFabnpIY0xhaTA0ci9QdU5HNHlq
        SDdxTWFUaVpza243U0lia3dYaUlleTQKNeuZzqkge8xCyGUVqgt6nDbLy7KcZm5s
        JiaMFO/1GQ2vT5a58VjSzrn0wkPn8C0Q7AjRboD89iB18VbBRAIkjA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-11T11:00:47Z"
  mac: ENC[AES256_GCM,data:NwaQ6KXDX7d8jS9QJYWDRgtPrq9wLAlOyEeaGgZ0zHFtwrbImMh47bl+QBCf1wdmhUPizvLU+va47jMqgpAeB1hzLwezO94TTEaQVSyAEZNgyXzgbWanUENKxYy89ixFr0eyQZaha1a7ddixUDX7c4gKUzM72GH6QROr7Ff5Bp8=,iv:DTSmMhveP6IohwI1VWho6P2iys8GsItk+keZ9KMffOU=,tag:U1rz6akBCwI4dL6Vi36lZw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
