apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: cluster-store-default-ns
spec:
  provider:
    kubernetes: &provider
      remoteNamespace: default
      server:
        url: 'https://kubernetes.default.svc.cluster.local'
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: default
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: cluster-store-velero-ns
spec:
  provider:
    kubernetes:
      remoteNamespace: velero
      server:
        url: 'https://kubernetes.default.svc.cluster.local'
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: default
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: cluster-store-volsync-ns
spec:
  provider:
    kubernetes:
      remoteNamespace: volsync
      server:
        url: 'https://kubernetes.default.svc.cluster.local'
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: default
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets
