---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Flux Local"

on:
  pull_request:
    branches: ["main"]
    paths:
      - kubernetes/apps/**
      - kubernetes/components/**
      - kubernetes/flux/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

  # - name: Get Keycloak version from GitRepository
  # run: |
  #   version=$(yq 'select(.kind == "GitRepository") | .spec.ref.semver' kubernetes/apps/keycloak/keycloak-operator/ks.yaml)
  #   echo "KEYCLOAK_K8S_RESOURCES_TAG=$version" >> $GITHUB_ENV
env:
  # renovate: datasource=github-releases depName=keycloak/keycloak
  KEYCLOAK_K8S_RESOURCES_TAG: 26.1.3

jobs:
  fetch_version:
    name: Fetch Keycloak Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  test:
    name: Flux Local Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get keycloak tag
        uses: mikefarah/yq@v4.45.2
        id: get_keycloak_version
        with:
          cmd: yq 'select(.kind == "GitRepository") | .spec.ref.semver' kubernetes/apps/keycloak/keycloak-operator/ks.yaml

      - name: Clone dependency repos
        run: git clone --branch "${{ steps.get_keycloak_version.outputs.result }}" https://github.com/keycloak/keycloak-k8s-resources.git "keycloak-k8s-resources" # FIXME do better

      - name: Run flux-local test
        uses: docker://ghcr.io/allenporter/flux-local:v7.5.0
        with:
          args: >-
            test
            --enable-helm
            --all-namespaces
            --path /github/workspace/kubernetes/flux/cluster -v
            --sources "flux-system,keycloak-k8s-resources=/github/workspace/keycloak-k8s-resources"

  diff:
    name: Flux Local Diff
    runs-on: ubuntu-latest
    needs: fetch_version
    permissions:
      pull-requests: write
      contents: read
    strategy:
      matrix:
        resources: ["helmrelease", "kustomization"]
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Checkout Pull Request Branch
        uses: actions/checkout@v4
        with:
          path: pull

      - name: Checkout Default Branch
        uses: actions/checkout@v4
        with:
          ref: "${{ github.event.repository.default_branch }}"
          path: default

      - name: Get keycloak tag
        uses: mikefarah/yq@v4.45.2
        id: get_keycloak_version
        with:
          cmd: yq 'select(.kind == "GitRepository") | .spec.ref.semver' pull/kubernetes/apps/keycloak/keycloak-operator/ks.yaml # it's other path to file than in test job!

      - name: Clone dependency repos
        run: git clone --branch "${{ steps.get_keycloak_version.outputs.result }}" https://github.com/keycloak/keycloak-k8s-resources.git "keycloak-k8s-resources" # FIXME do better

      - name: Run flux-local diff
        uses: docker://ghcr.io/allenporter/flux-local:v7.5.0
        with:
          args: >-
            diff ${{ matrix.resources }}
            --unified 6
            --path /github/workspace/pull/kubernetes/flux/cluster
            --path-orig /github/workspace/default/kubernetes/flux/cluster
            --strip-attrs "helm.sh/chart,checksum/config,app.kubernetes.io/version,chart"
            --limit-bytes 10000
            --all-namespaces
            --sources "flux-system,keycloak-k8s-resources=/github/workspace/keycloak-k8s-resources"
            --output-file diff.patch

      - name: Generate Diff
        id: diff
        run: |
          cat diff.patch;
          {
              echo 'diff<<EOF'
              cat diff.patch
              echo EOF
          } >> "$GITHUB_OUTPUT";
          {
              echo "### Diff"
              echo '```diff'
              cat diff.patch
              echo '```'
          } >> "$GITHUB_STEP_SUMMARY"

      - if: ${{ steps.diff.outputs.diff != '' }}
        name: Add Comment
        uses: mshick/add-pr-comment@v2
        with:
          message-id: "${{ github.event.pull_request.number }}/kubernetes/${{ matrix.resources }}"
          message-failure: Diff was not successful
          message: |
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```

  flux-local-success:
    needs: ["test", "diff"]
    if: ${{ always() }}
    name: Flux Local successful
    runs-on: ubuntu-latest
    steps:
      - name: Check flux-local status
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
